### ISSUE TITLE
Unlock Timeout Error when running keynote manager

### ISSUE THREAD

**Issue by 00brenTRON00** [pyrevitlabs/pyRevit#1725]
**Describe the bug**
I am in a workshared Revit project that is hosted on BIM 360.  A handful of my team members get the following error when trying to use keynote manager: "Wait for unlock timeout."  
I have checked the directory for the keynote file and I can see there is a .lock file, so I have deleted it.  And I have unlocked the keynote file.
I believe the .lock file was left there after one team member's computer crashed.

Since then though, a handful of us cannot use keynote manager.  We still get the "Wait for Unlock to Timeout." error.

I've also noticed that once we attempt to open keynote manager and get the error, it then locks the keynote file on the BIM 360 server and we must manually unlock it in the file browser.  But no .lock file is created.

**To Reproduce**
I simply open the project in Revit
Select the Kenote Manager command
Program waits for about 30 seconds then the error is displayed

**Expected behavior**
Normally, doing the above opens the Keynote manager

**Screenshots**
Here is the error and details
![image](https://user-images.githubusercontent.com/104477181/217046099-4a658e20-b311-4572-8fd5-2705f543231b.png)
Here is what the directory looks like both on my machine and on BIM 360
![image](https://user-images.githubusercontent.com/104477181/217046342-9604cda4-79f2-4c81-a077-7f82bbbb3ad9.png)
![image](https://user-images.githubusercontent.com/104477181/217046535-f505a5af-56c7-4257-89c5-a31f425efd7f.png)
Here is the actual keynote file:
[Keynotes - New Wasatch High School.txt](https://github.com/eirannejad/pyRevit/files/10667665/Keynotes.-.New.Wasatch.High.School.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - pyRevit Version :  4.8.12.22247+0031
 - pyRevit Environment:

**Comment by jmcouffin** [comment]
related https://github.com/pyrevitlabs/pyRevit/issues/2388
will be treated at the same time
