### ISSUE TITLE
Color Splasher suggestions

### ISSUE THREAD

**Issue by Thomas84** [pyrevitlabs/pyRevit#2027]
- Creating a range of values, instead of hundreds of colors (for example wall area or volume) would be nice. For example creating a range with maximum of 10 colors. Otherwise the legend is super large. 
- Selecting multiple Values to choose a color would be nice.  
- Add a Close dialog button
- allow to resize the dialog

**Comment by jmcouffin** [comment]
> * Add a Close dialog button

There is the X at the top right. Not enough?


> * Creating a range of values, instead of hundreds of colors (for example wall area or volume) would be nice. For example creating a range with maximum of 10 colors. Otherwise the legend is super large.

Feel free to sketch the logic.



> * Selecting multiple Values to choose a color would be nice.

Quite a headache to implement properly, the logic behind, mixing or not mixing parameters based on types.
You can style apply for a first param then do the next. 
I think keeping it simple is required here.
I don't want the tool to become an unmanageable beast



> * allow to resize the dialog

I will be as lazy as Autodesk on this one ;p

**Comment by jmcouffin** [comment]
Thanks for the suggestions

**Comment by jmcouffin** [comment]
I will add here a new suggestion from @jhtacoma

> I might offer one suggestion regarding the colour splasher, and that is to provide a wider (or brighter) range of colours -- or is this something I can tweak myself in the ColorSplasher.pushbutton/script.py file? I noticed that if more than 5 or 6 items are being differentiated by colour, it's easy for a couple of them to look pretty similar, probably due to having low brightness levels. Even after clicking repeatedly to re-randomize the colours, I found that some confusion between the different colours was still likely.

**Comment by jmcouffin** [comment]
- [ ] range of / brighter colours
- [ ] add close dialog button
- [ ] Selecting multiple Values to choose a color would be nice
