### ISSUE TITLE
Color Splacher Bugs

### ISSUE THREAD

**Issue by Jgarcia094** [pyrevitlabs/pyRevit#2067]
**🙏 I don´t see any of this bugs reported.

# 🐞 Describe the bug

These are the bugs I've encountered, after half a dozen experiences using this feature:
1. The parameter choice list displays several repeats and parameter names that are not available for the category (this one refered in one report).

3. If the font size on the computer is enlarged above the recommended value (150%), the text of the dialog box is partially obscured (see image). Tested on a 4K screen with 175% enlarged text.

4. When the parameter refers to a linear dimension (formatted by Length in Units) and the project unit for Length is meters or centimeters (and not milimeters), the filter values are wrong (see image).

# ♻️ To Reproduce
--

# ⏲️ Expected behavior
--

# 🖼 Screenshots of the issue
![PyREVIT Color Splasher errors](https://github.com/eirannejad/pyRevit/assets/75981500/0a13b5d7-dd19-404a-b17f-2b1ba6ca2b00)

# 🖥️ Hardware and Software Setup (please complete the following information):
 - Windows 2011 (not the W10 indicated in User Environment data)
 - With admin acess, contrary to extrated in User Environment data
 - pyRevit Version 4.8.14.24016
 - Used in REVIT 2024.2
 - pyRevit Environment: 
 
 ```==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.14.24016+1909" | Path: "C:\Users\JGarcia\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "24.2" | Engine: IPY277 (277) | Path: "C:\Users\JGarcia\AppData\Roaming\pyRevit-Master"
master | Product: "24.2" | Engine: IPY277 (277) | Path: "C:\Users\JGarcia\AppData\Roaming\pyRevit-Master"
master | Product: "23.1.3" | Engine: IPY277 (277) | Path: "C:\Users\JGarcia\AppData\Roaming\pyRevit-Master"
master | Product: "23.1.2" | Engine: IPY277 (277) | Path: "C:\Users\JGarcia\AppData\Roaming\pyRevit-Master"
master | Product: "2022.1.4" | Engine: IPY277 (277) | Path: "C:\Users\JGarcia\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\JGarcia\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit LT 2024\"
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
23.1.2 | Version: 23.1.20.70 | Build: 20230510_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023"
2022.1.4 | Version: 22.1.40.58 | Build: 20230505_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
PID: 26704 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
==> User Environment
Microsoft Windows 10 [Version 10.0.22631]
Executing User: PC_JG\JGarcia
Active User: PC_JG\JGarcia
Admin Access: No
%APPDATA%: "C:\Users\JGarcia\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.14.24016+1909.ee814ee2f686d23db8bb6ff80d8bb918ff9adc99
PS C:\Users\JGarcia>```

**Comment by jmcouffin** [comment]
1. Yep, something I know, and Revit Devs know too as it is following / providing the "complete" list of parameters through the Revit API. I could make it a set() by with the risk to miss some of them, there are different cases that I know of: 

> Category returns nothing, Worksets returns the list of workset for one, Design Option seems to have twice the same values (maybe due to cats like walls and curtain walls or inplace walls)., Railings are a good example, thanks, I would need to check what if the common denominator, but for now I would rather leave as is, rather than pretending that the tool provides all the parameters when I would do some post processing to remove the double parameters. What do you think.

Maybe checking if they hold value could help. I will keep the issue opened specifically to fix this one.

- [ ] multiple parameters with same name @jmcouffin 

2. I can't reproduce. I tried on Win10, Revit 2021 and 2024 @ 150% 175% 200% display and got this, no issue
![image](https://github.com/eirannejad/pyRevit/assets/7872003/4fe480b1-ee62-4f6f-82be-ece49744310a)
It may be more of a Revit option or graphics card capabilities issue, IMHO. If you get the chance, try to reproduce on a different computer. That would help.

3. I can't reproduce.

![image](https://github.com/eirannejad/pyRevit/assets/7872003/065331f6-c2ad-43ce-81a0-f9f46cbe0c06)

**Comment by Jgarcia094** [comment]
Jean-Marc, thanks for your answer.

Related to topic 3, the problem can´t be seen in the imagens that you posted.
The values in filter names are correct in meters (as in you images), but the correspondent values in Filters RULES are not in meters, and need to be manualy changed, as you can see in the attached image.
![PyREVIT Color Splasher Filter value error](https://github.com/eirannejad/pyRevit/assets/75981500/cdeec5a0-57b1-4a65-8f58-9d3a2e1dff01)

**Comment by jmcouffin** [comment]
> the problem can´t be seen in the imagens that you posted

yes, omission on my side, but trust me, I checked :) 
can you show your units setup?

**Comment by Jgarcia094** [comment]
Good morning,

See, in the attached image, my Project Units definition. See also 2 new tests with another categories and the same problem.

I used REVIT 2024.2, but I tried in my REVIT 2022.1 also and the problem is the same.

If Length parameter  = millimeters, the  Filter Rules values are correct.


Regards

José Manuel Garcia
***@***.******@***.***>
Tel. 917 152 158

De: Jean-Marc Couffin ***@***.***>
Enviada: 29 de janeiro de 2024 11:15
Para: eirannejad/pyRevit ***@***.***>
Cc: Jgarcia094 ***@***.***>; Author ***@***.***>
Assunto: Re: [eirannejad/pyRevit] Color Splacher Bugs (Issue #2067)


the problem can´t be seen in the imagens that you posted

yes, omission on my side, but trust me, I checked :)
can you show your units setup?

-

**Comment by jmcouffin** [comment]
@Jgarcia094 the image did not go through when you replied to the github email
It does not take attachments

**Comment by Jgarcia094** [comment]
![Color Slpacher Filter values error and Project Units](https://github.com/eirannejad/pyRevit/assets/75981500/660dcaf0-6bb5-4140-bd08-5db726a2c77f)

**Comment by Jgarcia094** [comment]
As soon as possible, I will try in other computers.

**Comment by Jgarcia094** [comment]
The error is related to the decimal separation symbol used and not to the unit chosen in the Length parameter. If the symbol is a comma and the decimal place number is equal to 2, the filter rule value is multiplied by 100, and is multiplied by 10 when the decimal place number is equal to 1. To avoid error, the separation symbol must be a dot.

**Comment by jmcouffin** [comment]
That helps a lot @Jgarcia094 thanks.
Would you care trying this fix on your install:

1. alt+click to find the file when clicking on the color splasher
https://github.com/eirannejad/pyRevit/blob/57c54be397a18b42cafd6319aa9d81a75bde8dac/extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py#L355

2. replace this
```python
                        value = float(sub("[^-\d|.]", "", item._value))
```
for
```python
                        value = float(sub("[^-\d|.|,]", "", item._value))
```

**Comment by Jgarcia094** [comment]
After changing “script.py” file and reinitiate REVIT, I received one error (attached image) that prevents filters from being created.
![Color splacher error](https://github.com/eirannejad/pyRevit/assets/75981500/7cd789e2-32ea-4880-81e7-87be9a49796f)

**Comment by jmcouffin** [comment]
Ok, I will have to dig deeper.
Kind of hard as I cannot reproduce the same things.

**Comment by Jgarcia094** [comment]
If you choose comma as decimal separator, you can't reproduce the error?
