### ISSUE TITLE
Keynote Manager Feature Instability 

### ISSUE THREAD

**Issue by FB-JHowe** [pyrevitlabs/pyRevit#2102]
Encountering an issue where the Keynote Manager feature within PyRevit causes Revit 2019 to freeze for certain keynote files. The issue persists across multiple installations (including a clean reinstall) of the add-in.

Findings:
- To my knowledge the problem occurs with specific keynote files, potentially hinting at file corruption or compatibility issues.
- A test with a new, clean keynote file indicated that the Keynote Manager can function correctly under certain conditions.
- No `.lock` files were found in the directory, even when checked through volume shadow copy, suggesting the issue may not be related to file locking. In addition, I do not see any locking information within the keynote file similar to what is shown in the 'Keynote Manager is Stuck' FAQ page- here's what I see in the locks table:
```
 # --------------------- @table(locks_table:"Locks Table") @sep("\t") @internal(yes) @tags(yes) @history(no) @encap(no) @headers(no) @key(lock_uuid) @uuid(lock_uuid:"") @text(lock_source:"") @text(lock_requester:"") @uuid(lock_conn_uuid:"") @text(lock_dbname:"") @text(lock_tablename:"") @text(lock_recordkey:"")
# ===================== @db(keynotesdb:"pyRevit Keynotes Manager DB")
```
- Permissions, antivirus configuration, group policy, and file server configurations were reviewed, with no clear obstacles identified that would prevent Pyrevit from working as it should. There is a policy designed to prevent crypto locker behavior by restricting certain executable code- however this is applied to all devices in the environment, yet only seems to effect one device/user. As best I can tell the restrictions should not be impacting Pyrevit / Revit. 

Temporary Workarounds:
- Creating a new keynote file from scratch.
- Attempting to restore an earlier backup of the keynote file, prior to potential corruption.

# ♻️ To Reproduce
1. Open Autodesk Revit 2019 with PyRevit (admin signed) 4.8.13.23182 
2. Click on Keynote Manager in Pyrevit ribbon when a keynote file has previously been created.
3. Observe that the feature does not work as expected, with Revit appearing frozen until the escape key is pressed. I believe a hidden popup may be generated, thus the escape key allowing revit to function again. 

Note, symptom does not occur when setting a new, blank keynote .txt file 

# ⏲️ Expected behavior
Keynote manager UI should open, even when working from a pre-existing keynote file. 

# 🖥️ Hardware and Software Setup (please complete the following information):
 - OS:  Microsoft Windows 10 Pro 10.0.19045
 - pyRevit Version  PyRevit (admin signed) 4.8.13.23182 
 - pyRevit Environment: 

```==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "Autodesk Revit 2023" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2023\pyRevit.addin"
Unknown | Product: "2021.1.2" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2021\pyRevit.addin"
Unknown | Product: "2019.2.2 Hotfix" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2019\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Installed Revits
==> Extension Sources - Additional
Autodesk Revit 2023 | Version: 23.1.20.70 | Build: 20230510_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2021.1.2 | Version: 21.1.20.44 | Build: 20201109_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2019.2.2 Hotfix | Version: 19.2.20.24 | Build: 20190808_0900(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 145220 | 2021.1.2 | Version: 21.1.20.44 | Build: 20201109_1530(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2021"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: MVEI\SYSTEM
Active User:
Admin Access: Yes
%APPDATA%: "C:\WINDOWS\system32\config\systemprofile\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.13.23182+2215
```

# Additional context
Note- I am an IT sys admin, not a BIM manager/design technology expert. So forgive my ignorance of Pyrevit's or Revit's actual functionality.

**Comment by jmcouffin** [comment]
related #2388 
will be treated at the same time
