### ISSUE TITLE
I need help because pyRevit v4.8.13.23182 doesn't work on Revit 2024

### ISSUE THREAD

**Issue by rebuenogan** [pyrevitlabs/pyRevit#2132]
> **🚧 If you have SentinelOne installed as an antivirus, look no further.**
> **You will need to create exceptions for Revit and pyRevit, both on the software and the %appdata% folders.**

SentinelOne is not installed

# ✈ Pre-Flight checks

We did the following troubleshooting steps: 

1. Uninstalled Pyrevit version 4.8.14
2. Removed %appdata%/pyrevit and %appdata%/pyrevit-master folder 
3. We went to C:\ProgramData\Autodesk\Revit\Addins\
4. Moved Revit add-ins to a temporary location
5. Restarted his computer
6. Installed Pyrevit version 4.8.13
7. Started Revit 2024 for a few minutes and then closed it
8. Brought back the Revit add-ins from the temporary location to C:\ProgramData\Autodesk\Revit\
9. Started Revit 2024
10. Pyrevit version 4.8.13 did not show up

# 🐞 Describe the bug

pyRevit v4.8.13.23182 add-in doesn't show up in Revit 2024

# ⏲️ Expected behavior

pyRevit v4.8.13.23182 add-in should show up in Revit 2024

# 🖥️ Hardware and Software Setup (please complete the following information)

Windows 11 Professional Edition (64-bit) 
pyRevit v4.8.13.23182

![92482_pyrevit_env](https://github.com/eirannejad/pyRevit/assets/162085175/6d39eccd-b96a-4060-8760-c3ab22264989)

# Additional context

We also uninstalled Visual Studio 2022 but that did not fix the missing pyRevit v4.8.13.23182 add-in in Revit 2024

**Comment by jmcouffin** [comment]
The version installed is not the latest release, I would start with that.

then try this command line and report please

`pyrevit attach master 2711 --installed --allusers`


if nothing works
try these https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7?pvs=74

**Comment by rebuenogan** [comment]
> The version installed is not the latest release, I would start with that.
> 
> then try this command line and report please
> 
> `pyrevit attach master 2711 --installed --allusers`
> 
> if nothing works try these https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7?pvs=74

Hi @jmcouffin these were the steps that we did today: 

1.) Ran CMD as an admin and then entered the command line: pyrevit attach master 2711 --installed --allusers
![image](https://github.com/eirannejad/pyRevit/assets/162085175/73ee7bf1-6a3b-480e-a6c8-73ccaac139e9)

2.) Opened Revit 2024 and we encountered this loading error
![image](https://github.com/eirannejad/pyRevit/assets/162085175/9d3bcb50-65c9-457d-9f97-4fec0a3aa2b0)

3.) Closed the loading error screen and Revit 2024

4.) Entered the command line: pyrevit attached

5.) Entered the command line: pyrevit attach master 2711 --installed  
![image](https://github.com/eirannejad/pyRevit/assets/162085175/4880375c-a65f-433a-8c48-76be8c5516a9)

6.) Opened Revit 2024 and we still encountered this loading error
![image](https://github.com/eirannejad/pyRevit/assets/162085175/2a0f5126-8b3b-42ec-b67f-85e2a8766f25)

The loading error screen doesn't look like the "Error dynamically compiling pyRevit runtime" that is shown in your link: https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7

**Comment by jmcouffin** [comment]
> The loading error screen doesn't look like the "Error dynamically compiling pyRevit runtime" that is shown in your link: https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7

Even though this is not the same exact error message, the solutions in the article do work for this.
Please do try them one at a time thoroughly.

**Comment by rebuenogan** [comment]
> > The loading error screen doesn't look like the "Error dynamically compiling pyRevit runtime" that is shown in your link: https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7
> 
> Even though this is not the same exact error message, the solutions in the article do work for this. Please do try them one at a time thoroughly.

Hi @jmcouffin we followed those steps today but the Pyrevit add-in is still not showing up 
![image](https://github.com/eirannejad/pyRevit/assets/162085175/5f1ff673-bd5b-4b7e-8cab-af63142d31f1)

**Comment by guusgooskens** [comment]
Hi @rebuenogan, @jmcouffin, we are receiving the same error message on Revit startup.

Did you manage to find a fix?

Our pyRevit env:

![image](https://github.com/eirannejad/pyRevit/assets/73542374/38bc2bda-4b58-4139-9587-7a6ca4ed6c1a)

**Comment by jmcouffin** [comment]
1. try uninstalling the current version and use one of the wip installers
2. if it does not work, try renaming the pyrevit.addin file to something like 0_pyrevit.addin, so that it loads first.
3. and if it still does not work: https://github.com/eirannejad/pyRevit/issues/2132#issuecomment-2028077188

**Comment by guusgooskens** [comment]
@jmcouffin thanks again!
We tried step 1 attaching WIP installer as you can see under clones, no luck I am afraid. Also not with other 2 steps.

Our user reporting this issue is running Windows 11, just like @rebuenogan. Could this cause the error?

**Comment by jmcouffin** [comment]
> @jmcouffin thanks again! We tried step 1 attaching WIP installer as you can see under clones, no luck I am afraid. Also not with other 2 steps.
> 
> Our user reporting this issue is running Windows 11, just like @rebuenogan. Could this cause the error?

it shouldn't, I run pyrevit on 2 computers one with win10 and the other with win11, no issue.
Most probably a addin incompatibility issi.
Step 3 works 99% of the time

**Comment by guusgooskens** [comment]
Ok thanks for confirming. We will try again

**Comment by jmcouffin** [comment]
I will consider it solved following these guidelines: https://github.com/pyrevitlabs/pyRevit/issues/2132#issuecomment-2028077188

**Comment by guusgooskens** [comment]
> 2. if it does not work, try renaming the pyrevit.addin file to something like 0_pyrevit.addin, so that it loads first.

This fixed the above error for all users. Could the next release possibly create the `_pyrevit.addin` file?

After the fix however, we are still getting the Error dynamically compiling pyRevit runtime.


I will refer users to [the installation issues guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7#ee9590e3dd8d4920b8b09ecb3c42d993), but it is hard to fix as no one has admin rights to edit Revit addins folders.
