### ISSUE TITLE
Revit 2025

### ISSUE THREAD

**Issue by jmcouffin** [pyrevitlabs/pyRevit#2190]
- [x] added Revit 2025 to pyRevit-hosts.json file
- [x] attach itself
- [x] Error on startup, pyRevit not loading (expected)

![image](https://github.com/eirannejad/pyRevit/assets/7872003/9d158689-d643-4d46-8091-42ebcffa8d3a)

**Comment by georgfaust** [comment]
can you estimate when pyRevit will work with 2025?

**Comment by jmcouffin** [comment]
> can you estimate when pyRevit will work with 2025?

No. It does not depend on me. Lots needs to be done. Very few are capable or have the time.

**Comment by trex246** [comment]
I am retired and use Revit, done a couple simple Dynamo's but not really good at this. I will help if there is grunt work or a direction I can get. I did update my hosts-json file as shown in a previous.

**Comment by MBM18** [comment]
Many thanks for this info as i got the same error on startup using Revit 2025 and have spent the last hour trying to find a solution. Will revert back to Revit 2024 i think now.

**Comment by naumanmy** [comment]
@jmcouffin Please let me know if I can assist in anyway.

**Comment by trex246** [comment]
If anyone has Betas on 2025 I would be interested in trying out on 2026 as well. I am Beta testing Revit 2026 and would like to try any versions for 2025 to see what can been done in advance for 2026. Thanks

**Comment by jmcouffin** [comment]
Please have a look at the wip installers
@ pyrevitlabs.io or in the actions tab for the develop branch

**Comment by jmcouffin** [comment]
> Does anyone else value the use of 'Match' feature? It was my primary item to use but it stopped working in my install of what I think is the latest 2025 Revit, The Shift-Click works to see and check or uncheck the Graphic Overides, but it does not 'paste' the Graphic Overrides to a selected item. Can anyone make this work?

Please open a new issue and provide details on your setup and install details
