### ISSUE TITLE
[Bug]: PyRevit is not showing inside Revit versions

### ISSUE THREAD

**Issue by JunoJolly** [pyrevitlabs/pyRevit#2217]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Hello Team,

We have installed PyRevit but the addon is not visible inside Revit.

### ⌨ Error/Debug Message

```shell
PyRevit is missing in Revit.

Tried running the command " pyrevit attach master 277 --installed " and got below error
Error: Can not find engine with specified version "277" is found
Run with "--debug" option to see debug messages
```

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
C:\Users\00jjolly>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.15.24089+0912" | Path: "C:\Users\00jjolly\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2024.0.2" | Engine: DEFAULT (2711) | Path: "C:\Users\00jjolly\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\00jjolly\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2024.0.2 | Version: 24.0.20.20 | Build: 20230509_0315(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
==> Running Revit Instances
PID: 3704 | 2024.0.2 | Version: 24.0.20.20 | Build: 20230509_0315(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Active User:
Admin Access: No
%APPDATA%: "C:\Users\00jjolly\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.15.24089+0912.f079f5fd51756b988a06d005d4f4cd2961f36e63
```

**Comment by jmcouffin** [comment]
pyrevit detects only 2024 version of revit, do you have any other Revit version installed? @JunoJolly

**Comment by JunoJolly** [comment]
We need to make this addin available to a group of users in our organization via Software center.
And we may need it for different versions of Revit.
Currently I am testing it only Revit 2024.

**Comment by jmcouffin** [comment]
and it is not showing in Revit 2024 after running the command?

**Comment by jmcouffin** [comment]
no reaction, closing the issue

**Comment by JunoJolly** [comment]
Sorry for the late reply.

Could you please confirm whether the pyrevit plugin will work for other version of Revit(2023,2022,2021).

**Comment by JunoJolly** [comment]
> and it is not showing in Revit 2024 after running the command?

After running the command it worked for Revit 2024 but would like to know whether it will work for other versions or not.

**Comment by jmcouffin** [comment]
It should

**Comment by JunoJolly** [comment]
In one of our test machine Revit 2024 and Revit 2023 are available,when running the command I am getting below error.
command " C:\Users\00jjolly>pyrevit attach master 2711 --installed
Error: Can not find clone "master"
Run with "--debug" option to see debug messages

**Comment by jmcouffin** [comment]
Run 'pyrevit envy
And see if you have a clone named master in the registered clones section of the output of the command
