### ISSUE TITLE
[Bug]: Add on Crashes on Revit startup

### ISSUE THREAD

**Issue by Pietieklipkop** [pyrevitlabs/pyRevit#2221]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

I installed the latest version of PyRevit with the aim on using it on Revit 22. After I installed it and open Revit I get a popup with a error stack.
![WhatsApp Image 2024-04-24 at 18 43 49_ad44e01e](https://github.com/eirannejad/pyRevit/assets/8450795/05226ed9-8d3f-404e-9797-a18677d5fd98)
![WhatsApp Image 2024-04-24 at 18 43 50_c0372a27](https://github.com/eirannejad/pyRevit/assets/8450795/c168b1c6-4324-421e-bbb3-8dd0e4f1ce46)

### ⌨ Error/Debug Message

```shell
System.MissingMemberException: 'NoneType' object has no attribute 'GetType'
```

### ⏲️ Expected behavior

The expected behavior is for Revit to start with PyRevit included so I can start using the Add on.

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
C:\Users\loure>pyrevit env.
Usage: pyrevit COMMAND [OPTIONS]

pyRevit environment and clones manager

    Options:
        -h --help                Show this help
        -V --version             Show version
        --usage                  Print all usage patterns
        --verbose                Print info messages
        --debug                  Print docopt options and logger debug messages
        --log=<log_file>         Output log messages to external log file

    Management Commands:
        env                      Print environment information
        update                   Update remote resources used by this utility
        clones                   Manage pyRevit clones
        extensions               Manage pyRevit extensions
        attached                 Manage pyRevit attachments to installed Revit
        releases                 Info about pyRevit releases
        revits                   Manage installed Revits
        caches                   Manage pyRevit caches
        configs                  Manage pyRevit configurations

    Commands:
        clone                    Create a clone of pyRevit on this machine
        extend                   Create a clone of a third-party pyRevit extension on this machine
        attach                   Attach pyRevit clone to installed Revit
        switch                   Switch active pyRevit clone
        detach                   Detach pyRevit clone from installed Revit
        config                   Configure pyRevit for current user
        run                      Run python script in Revit
        doctor                   Fix potential or real problems

    Help Commands:
        wiki                     Open pyRevit Wiki
        blog                     Open pyRevit blog
        docs                     Open pyRevit docs
        source                   Open pyRevit source repo
        youtube                  Open pyRevit on YouTube
        support                  Open pyRevit support page

Run 'pyrevit COMMAND --help' for more information on a command.
```

### Additional context

I have used PyRevit on this PC in the past, up until I installed the latest version, then this error started to occur. I have reinstalled PyRevit and Revit to try to fix the issue.

**Comment by jmcouffin** [comment]
no reactions, closed
