### ISSUE TITLE
PyRevitLoader - Error Loading pyRevit in 2023 and 2024[Bug]: 

### ISSUE THREAD

**Issue by BundFang** [pyrevitlabs/pyRevit#2236]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

I uninstalled pyRevit and ran the pyRevit v4.8.16.24121. After restarting my computer and opening Revit 2023 and 2024, I got the attached error. Any fix?

![image](https://github.com/pyrevitlabs/pyRevit/assets/168624779/e369b4d7-9cc1-4fcc-85a5-61dc2f3692ac)
![2024-05-01 09_07_23-](https://github.com/pyrevitlabs/pyRevit/assets/168624779/d1bc8428-9c75-47e8-bc53-4d4c0f8a3583)

### ⌨ Error/Debug Message

```shell
none
```

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Windows 10 Business
```

**Comment by jmcouffin** [comment]
First you can try renaming the pyrevit.addin file appending a 0 to it so that it loads first.

**Comment by pippo-82** [comment]
> Hi @BundFang, Try these steps:
> 
> 1. Uninstall pyRevit
> 2. Delete C:\ProgramData and %AppData%\ pyRevit and pyrevit-master folders
> 3. Move all Revit addins to a temporary location. Usual addins locations include:
>    
>    * %AppData%\Autodesk\Revit\Addins
>    * %AppData%\Autodesk\ApplicationPlugins
>    * %ProgramData%\Autodesk\Revit\Addins
>    * %ProgramData%\Autodesk\ApplicationPlugins
> 4. [Reboot computer]
> 5. Reinstall pyRevit
> 6. Started each version of Revit confirming pyRevit successfully compiled at startup.
> 7. Move all Revit addins that were moved in step 3 back to their original location.
>    You may want to add them one at a time and start a revit session everytime to figure out which ones are causing the issue.

Had the same issue and solved with all the steps you listed.
In my case I had no addins causing the issue.

PP

**Comment by jmcouffin** [comment]
> In my case I had no addins causing the issue

Many Revit functionalities are treated as addin in Revit.

**Comment by BundFang** [comment]
Thank you everyone!
The below steps helped.

> Hi @BundFang, Try these steps:
> 
> 1. Uninstall pyRevit
> 2. Delete C:\ProgramData and %AppData%\ pyRevit and pyrevit-master folders
> 3. Move all Revit addins to a temporary location. Usual addins locations include:
>    
>    * %AppData%\Autodesk\Revit\Addins
>    * %AppData%\Autodesk\ApplicationPlugins
>    * %ProgramData%\Autodesk\Revit\Addins
>    * %ProgramData%\Autodesk\ApplicationPlugins
> 4. [Reboot computer]
> 5. Reinstall pyRevit
> 6. Started each version of Revit confirming pyRevit successfully compiled at startup.
> 7. Move all Revit addins that were moved in step 3 back to their original location.
>    You may want to add them one at a time and start a revit session everytime to figure out which ones are causing the issue.
