### ISSUE TITLE
show view range - match view extents

### ISSUE THREAD

**Issue by RevitIRL** [pyrevitlabs/pyRevit#2245]
## Is your feature request related to a problem? Please describe

Trying to show users visually what is in a plan view

## Describe the solution you'd like

Color planes should match what's shown in the view (not the extents of Level1)

## Describe alternatives you've considered

grin & bear it :)

**Comment by thumDer** [comment]
It was intentional to use the level, because calculating a views outline can be tricky if it is not cropped. An alternative could be to use the view's outline if it is croped but fallback to the level's if it is not.

**Comment by RevitIRL** [comment]
I'd prefer that method - and that's what I would expect (using the view's Associated Level if no Crop Region).

from the other thread:
maybe you could get the bounding box of the view instead? [though it would be nice,] If it's not precisely the outline of the crop region, that's fine (i.e. it can be rectangular), but sometimes our level is huge, but the plan view is smaller

**Comment by thumDer** [comment]
The extents if the crop is easy. If there is no crop the extents has to be calculated from the complete model and that is quite expensive.

**Comment by thumDer** [comment]
I've changed the code to use the views extents. Do we need the level's extents as a fallback, or should the UI warn about turning on the crop? I think the different behaviour for uncropped views can be confusing without explanation, and most of the views are cropped anyway.
Thoughts? @RevitIRL @jmcouffin

**Comment by jmcouffin** [comment]
@thumDer I'd go for the warning IMHO

**Comment by thumDer** [comment]
I've also realized that I would need to combine that pre-check/warning with the 3d view's sectionbox check, because if the 3d view has a section box the script will use its extents for the planes, and the levels were only a fallback. So now the crop will be a fallback, and if there is none the warning will ask the user to turn on the section box OR the crop. Deal?

**Comment by jmcouffin** [comment]
@thumDer deal
One thing I noticed is that in the Revit sample house (imperial) the plans are offset up by the inverse of the project base point vertical displacement

**Comment by thumDer** [comment]
@jmcouffin  Interesting. I don't have the imperial sample house right know, could you send it over to me somehow?

**Comment by thumDer** [comment]
thanks, already fixed by https://github.com/pyrevitlabs/pyRevit/commit/5ddd651c72b28bad823e1316ef3654fa0571e004
we always have our PBP at our internal origin, so never came accross this difference, but nice catch!

**Comment by jmcouffin** [comment]
shall we close the issue?

**Comment by thumDer** [comment]
That fix I comitted is only for the elevation issue, I still need some time to finalize to crop based extents, only slight adjustments, safeguard mechanisms.

**Comment by jmcouffin** [comment]
Manually, that makes me feel better to see the number of issues going down, that's me liking things tidy🤭
