### ISSUE TITLE
show view range - enable for other view types (Sections, Details, etc.

### ISSUE THREAD

**Issue by RevitIRL** [pyrevitlabs/pyRevit#2246]
## Is your feature request related to a problem? Please describe

You can see it in plan & other sections, and you can change the 3D view to only show the section's extents, but it would be nice to have it seen in a larger context.

## Describe the solution you'd like

Be able to select other views, not just plans

## Describe alternatives you've considered

This would really just be a bonus to a bonus, so not a big deal to not have :)

**Comment by thumDer** [comment]
I was also thinking about this extended functionality, and in theory it is not that complicated. There won't be any info about the extents on the UI though. Let's keep the issue open, and I will evaluate.

**Comment by RevitIRL** [comment]
not sure if you could handle split segments (where the cut plane jogs), but not showing the extents in the UI is ok since Far Clip Offset is shown directly in Properties pane

but now that I'm thinking about it, adding section functionality would be most useful if multi-selection was also allowed (so could see if the section was within the extents of a plan, and therefore visible)
