### ISSUE TITLE
show view range - account for Plan Regions

### ISSUE THREAD

**Issue by RevitIRL** [pyrevitlabs/pyRevit#2247]
## Is your feature request related to a problem? Please describe

I can't believe I didn't think of this right away, but this is actually huge!

## Describe the solution you'd like

account for settings & extents of Plan Regions when drawing the planes

## Describe alternatives you've considered

This is nice as-is to illustrate the setting for training purposes, but without accounting for Plan Regions the usefulness for troubleshooting is severely limited as-is

**Comment by thumDer** [comment]
This is actually a nice idea, but can be complicated UX wise (especially after the recent updates I made for #2245 ). The whole business logic is tied to the selection made in the project browser. I'll have to check how difficult this would be.

**Comment by jmcouffin** [comment]
thanks @thumDer I guess we can dismiss and close this one.
