### ISSUE TITLE
Automatically reduce the number of model faces

### ISSUE THREAD

**Issue by jingyangking** [pyrevitlabs/pyRevit#2249]
Hello developer, I would like to know how to use this tool to automatically reduce the number of faces in IFC or REVIT models, and can also set the level of face reduction. thanks

**Comment by jmcouffin** [comment]
There is no builtin tools in pyRevit for that.
Best way to proceed is by first avoid modeling curved and round object. IFC tesselates curves and round object which increases IFC file size.
This is a task that would require a custom exporter for IFC or some sort of custom geometry engine to handle this exportation process.

**Comment by jmcouffin** [comment]
I do have a tool that checks the number of faces of family types making a pseudo export. This is an inhouse tool, I will see if I can make it available to the wider community
@jingyangking

**Comment by jingyangking** [comment]
> I do have a tool that checks the number of faces of family types making a pseudo export. This is an inhouse tool, I will see if I can make it available to the wider community @jingyangking

I have searched many places but still haven't found the corresponding tools, which shows a lack of knowledge in this related field. If you can provide this tool, I think it must be very cool.

**Comment by jmcouffin** [comment]
@jingyangking I asked my company, BIM One Inc., if I could give away this piece of code I developed and they agreed.
The tool will be available after the CI ends, in the WIP installers: https://github.com/pyrevitlabs/pyRevit/actions/runs/9170830079

It won't give you the ability to reduce faces by itself, but will at least give you insights about the faces count per family type.
![faces counter](https://github.com/pyrevitlabs/pyRevit/assets/7872003/2b107b73-148b-470a-a70b-ae4022189e4b)

**Comment by jmcouffin** [comment]
I will close the topic. If you find ways to simplify geometries easily, please feel free to reopen.
