### ISSUE TITLE
[Bug]: Installer installs an incorrect .addin file

### ISSUE THREAD

**Issue by IanCundall** [pyrevitlabs/pyRevit#2250]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

On my machine which has Revit 2020, 2021, 2022, 2023 & 2024 installed, the pyRevit.addin file is pointing at "<Assembly>C:\Program Files\pyRevit-Master\bin\engines\IPY277\pyRevitLoader.dll</Assembly>"

However, the installer (https://github.com/pyrevitlabs/pyRevit/releases/download/v4.8.16.24121%2B2117/pyRevit_4.8.16.24121_admin_signed.exe) installs to:
"C:\Program Files\pyRevit-Master\bin\engines\CPY385"
"C:\Program Files\pyRevit-Master\bin\engines\IPY340PR"
"C:\Program Files\pyRevit-Master\bin\engines\IPY2711PR"
"C:\Program Files\pyRevit-Master\bin\engines\CPY378"

The same occured on a machine with only Revit 2023 installed.

### ⌨ Error/Debug Message

```shell
Revit versions all pop up the standard "Revit cannot load..." message, pointing to the "missing" assembly.
```

### ♻️ To Reproduce

- Install Revit
- Install pyRevit 4.8.16
- Start Revit

### ⏲️ Expected behavior

Revit should prompt the user to trust the add-in

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
==> Attachments
Unknown | Product: "24.2" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2024\pyRevit.addin"
Unknown | Product: "23.1.3" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2023\pyRevit.addin"
Unknown | Product: "2022.1.5" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2022\pyRevit.addin"
Unknown | Product: "2021.1.9" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2021\pyRevit.addin"
Unknown | Product: "2020.2.9" | Manifest: "C:\ProgramData\Autodesk\Revit\Addins\2020\pyRevit.addin"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\[user ID redacted]\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.9 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.22621]
Executing User: [domain name redacted]\[user ID redacted]
Active User:
Admin Access: No
%APPDATA%: "C:\Users\[user ID redacted]\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.16.24121+2117.23a0b8cbc4babdeb29a0611e159d017bbe9cbad5
```

**Comment by IanCundall** [comment]
>No .Ne-Core Target Packs are installed.
I suspect this message should say:
No .Net Core Target Packs are installed.

**Comment by jmcouffin** [comment]
> ```shell
> No .Ne-Core
> ```

Typo is fixed  in develop-4 branch. 
Latest WIP installer will issue the fix.
Thanks, 

The rest of the issue is more complicated and will be looked whenever possible

**Comment by sanzoghenzo** [comment]
HI @IanCundall,
have you tried to `pyrevit attach 2711`? the IronPython 2.7.7 engine was removed in the latest version of pyrevit, and it probably the installer didn't update the .addins file to point to the new location.

**Comment by IanCundall** [comment]
I am not an end-user and have no clue how to drive pyRevit and even as an IT veteran of some 40 years, I'm afraid I find the help and documentation to be quite opaque. 

I tried 'pyrevit attach 340' (as 340 is contained in the name of the actual path), I get a 'help' screen which indicates to me that it didn't like that command. I get exactly the same response with 'pyrevit attach 2711' as suggested above.

I'd much prefer for the installer to simply copy in a pyrevit.addin file which contains the correct path, i.e. in this case, C:\Program Files\pyRevit-Master\bin\engines\IPY340PR

**Comment by sanzoghenzo** [comment]
We need to create the addin file dynamically because of the architecture of pyRevit (pyRevit itself needs an IronPython engine, and it needs to be the same that the user wants to run for their buttons).

We have planned to move everything "pyRevit core" to C# in order to break free from this dependency and be able to use a fixed .addin file.

That being said, I see from the pyrevit env output that there's no pyRevit clones (installation) available.

Try these two commands:

```
pyrevit clone master
pyrevit atttach master default --installed
```

**Comment by IanCundall** [comment]
When I ran 'pyrevit clone master', I got:

```
Error: certificate revocation status could not be verified.
Run with "--debug" option to see debug messages
```
When I included '--debug', I got:

```
clone = True
<clone_name> = master
Debug: Checking for all: wiki
Debug: Missing: wiki
Debug: Checking for all: blog
Debug: Missing: blog
Debug: Checking for all: docs
Debug: Missing: docs
Debug: Checking for all: source
Debug: Missing: source
Debug: Checking for all: youtube
Debug: Missing: youtube
Debug: Checking for all: support
Debug: Missing: support
Debug: Checking for all: env
Debug: Missing: env
Debug: Checking for all: update
Debug: Missing: update
Debug: Checking for all: clone
Debug: Repo source determined as "https://github.com/pyrevitlabs/pyRevit.git:master"
Debug: Destination path determined as "C:\Users\adminin\AppData\Roaming\pyRevit\pyRevit"
Debug: Destination path already exists C:\Users\adminin\AppData\Roaming\pyRevit\pyRevit
Debug: Using subpath C:\Users\adminin\AppData\Roaming\pyRevit\pyRevit\master
Debug: Cloning "https://github.com/pyrevitlabs/pyRevit.git:master" to "C:\Users\adminin\AppData\Roaming\pyRevit\pyRevit\master"
Error: certificate revocation status could not be verified (pyRevitLabs.Common.PyRevitException)
   at pyRevitLabs.Common.GitInstaller.Clone(String repoPath, String branchName, String destPath, GitInstallerCredentials creds, Boolean checkout)
   at pyRevitLabs.PyRevit.PyRevitClones.DeployFromRepo(String cloneName, String deploymentName, String branchName, String repoUrl, String destPath, GitInstallerCredentials credentials)
   at pyRevitCLI.PyRevitCLICloneCmds.CreateClone(String cloneName, String deployName, String branchName, String repoUrl, String imagePath, String destPath, GitInstallerCredentials credentials)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)

```

**Comment by sanzoghenzo** [comment]
Do you use symantec/broadcom wss or some other internet security tool that monitors https traffic? 
They can interfer with the download/clone from github

**Comment by IanCundall** [comment]
Hi.

Please close the ticket. Our network protection tool Netskope was preventing access to GitHub.

**Comment by jmcouffin** [comment]
@sanzoghenzo you get a new chip 🍾
