### ISSUE TITLE
[Bug]: Sync View and Make Pattern tool not working properly

### ISSUE THREAD

**Issue by useromi** [pyrevitlabs/pyRevit#2261]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Sync View and Make Pattern tools not working properly as should be working while I'm trying to use these tools views are not synced with each other. The same in the case of the Make Pattern tool it can't update the existing pattern after creating a new pattern.

### ⌨ Error/Debug Message

```shell
there is no error message after debugging.
```

### ♻️ To Reproduce

There is no Error while checking for debugging. Tool button is working properly according to debugging ctrl+click.

### ⏲️ Expected behavior

Views are not sycronize with each other.

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.14.24016+1909" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "23.1.2" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2022.1.3" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\orb\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
23.1.2 | Version: 23.1.20.70 | Build: 20230510_1100(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.3 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
PID: 24948 | 2022.1.3 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2022"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: MPES\orb
Active User: MPES\orb
Admin Access: No
%APPDATA%: "C:\Users\orb\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.14.24016+1909.ee814ee2f686d23db8bb6ff80d8bb918ff9adc99
```

**Comment by jmcouffin** [comment]
You need to provide more details:
For the **sync view** tool
- what type of views are you trying to sync?
- same levels?

For the Pattern Tool: 
- Type of pattern
- from an import
- anything that would give some food for thought (and trials)

**Comment by useromi** [comment]
For the sync view 
1.  I'm working on 2 same duplicate floorplan views.
2.  Yes, same-level duplicate views.

For the Pattern Tool
1.  I'm creating a custom pattern by detail line.
2. Not from import trying to create in Revit by detail line tool.
3. after debugging by pressing ctrl+click on the icon script seems working without error but in the Revit these tools not working properly.

**Comment by jmcouffin** [comment]
> * I'm working on 2 same duplicate floorplan views.
> * Yes, same-level duplicate views.

Just tried it, with the latest version of pyRevit, duplicated view plan. It works fine.
![2024-05-17_11-31-05](https://github.com/pyrevitlabs/pyRevit/assets/7872003/718fcd01-a017-4f60-997b-735415bb361a)

**Comment by jmcouffin** [comment]
> For the Pattern Tool
> 
> 1. I'm creating a custom pattern by detail line.
> 2. Not from import trying to create in Revit by detail line tool.

tried it too: 
- selected original lines used to build the pattern after modifying them
- clicked the tool
- set the same name
- set to create the filled region again
it worked.

btw, you are using an old version of pyRevit _ not that it will change anything as the code for the tool hasn't changed much in years

I will close for now unless you have more meat to provide

**Comment by jmcouffin** [comment]
and please next time: two bugs for two different tools -> two issues
