### ISSUE TITLE
[Bug]: Pyrevit Error Load

### ISSUE THREAD

**Issue by Baalane** [pyrevitlabs/pyRevit#2264]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Hello,

I am once again encountering the same problem with loading Pyrevit on Revit.
When I faced this issue a few months ago, I understood that there was a conflict with plugins, and there were two methods to resolve it.
First, uninstall all other plugins and then reinstall only Pyrevit to load it and then install the other plugins afterward. The other method was similar but involved moving the plugins folder so that they wouldn’t load in Revit at startup.
When I used the first method, it worked.

However, I am currently experiencing the same issue. While Pyrevit worked very well on Revit 2022, after installing Revit 2024, it no longer works and shows the error message at launch. Additionally, it no longer works on Revit 2022 either.
![Capture pyrevit](https://github.com/pyrevitlabs/pyRevit/assets/151652483/7a0b6b5c-f5e1-4d46-beb9-2dc9d224c82f)

### ⌨ Error/Debug Message

```shell
I tried to uninstall all other plugins and nothing change
```

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Microsoft Windows [version 10.0.19045.4412]
(c) Microsoft Corporation. Tous droits réservés.
 
C:\Users\User>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.15.24089+0912" | Path: "C:\Users\User\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2024" | Engine: DEFAULT (2711) | Path: "C:\Users\User\AppData\Roaming\pyRevit-Master"
master | Product: "2023.1.1" | Engine: DEFAULT (2711) | Path: "C:\Users\User\AppData\Roaming\pyRevit-Master"
master | Product: "2022.1.5" | Engine: DEFAULT (2711) | Path: "C:\Users\User\AppData\Roaming\pyRevit-Master"
master | Product: "2021.1.9" | Engine: DEFAULT (2711) | Path: "C:\Users\User\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.9" | Engine: DEFAULT (2711) | Path: "C:\Users\User\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\User\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2024 | Version: 24.1.11.26 | Build: 20230911_1230(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
2023.1.1 | Version: 23.1.10.4 | Build: 20221122_1550(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.9 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 13652 | 2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2022"
PID: 26008 | 2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2022"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: Domain\User
Active User: Domain\User
Admin Access: No
%APPDATA%: "C:\Users\User\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.16.24121+2117.23a0b8cbc4babdeb29a0611e159d017bbe9cbad5
```

**Comment by sanzoghenzo** [comment]
Hi @Baalane, did the instructions in the previous post solve the issue for you?

/more-info

**Comment by Baalane** [comment]
Hello i tried a different thing, 
Move all Revit addins to a temporary location and then go into these folders 

%appdata%\pyRevit
%appdata%\Autodesk\Revit\Addins

And delete the Revit version folder in my case it was 2024
Then i open a cmd and attached pyrevit with Revit 
pyrevit attach master 2711 --installed

It create new 2024 folders and then i started R24 and it works

**Comment by sanzoghenzo** [comment]
Im glad you solved! Closing this issue
