### ISSUE TITLE
[Bug]: Failure to Launch in Revit 2025

### ISSUE THREAD

**Issue by wghuser** [pyrevitlabs/pyRevit#2265]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Failure to launch pyrevit

![image](https://github.com/pyrevitlabs/pyRevit/assets/170440160/6186f22d-dfa4-41c7-a01e-98721d2497a3)

### ⌨ Error/Debug Message

```shell
see screenshot
```

### ⏲️ Expected behavior

Launch pyrevit

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Windows 10 on OptiPlex XE4
```

**Comment by jmcouffin** [comment]
Pyrevit is not Revit 2025 ready yet. It might take some time.

**Comment by wghuser** [comment]
Hello,

Do you have a timeline for PyRevit compatibility with Revit 2025?

Thanks

**Comment by jmcouffin** [comment]
same canned answer for everyone
no ETA
https://github.com/pyrevitlabs/pyRevit/issues/2190

**Comment by imtiaz2025** [comment]
Hello, sir. Is there an expected release date for PyRevit for Revit 2025?
