### ISSUE TITLE
Won't install in Revit 2024

### ISSUE THREAD

**Issue by JeffatMandF** [pyrevitlabs/pyRevit#2266]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

When I try following the troubleshooting instructions, it shows that pyRevit is installed in 2022, but it won't attach to 2024.

### ⌨ Error/Debug Message

```shell
C:\Users\Jeff Lotz.MANDF>pyrevit attached
==> Attachments
Unnamed-363FBF8 | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
```

### ♻️ To Reproduce

Open a command prompt and run pyrevit attached

### ⏲️ Expected behavior

This is what it's supposed to look like:
==> Attachments
master | Product: "2020.1 Update" | Engine: IPY277 (277) | Path: "....."
master | Product: "2019.2.2 Hotfix" | Engine: IPY277 (277) | Path: "....."

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Dell Precision T3610
Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz, 3701 Mhz, 4 Core(s), 4 Logical Processor(s)
running Windows 10 Pro
```

### Additional context

This is a networked environment. I have looked at the forums and haven't found any with the "Unnamed-363FBF8." I'm not a programmer and this is all way beyond me. Any help would be greatly appreciated. Thanks.

**Comment by jmcouffin** [comment]
Can you uninstall and download the latest release and try to install again.
The engine mentioned in your env result tends to show that you are using an old version of pyrevit

**Comment by JeffatMandF** [comment]
You were right. The latest version didn't overwrite the old version. I followed your instructions and it worked. Thank you so much!


Jeff Lotz, Assoc. AIA

Designer

***@***.******@***.***>


Margolis + Fishman

[cid:a65f4949-89e9-49bb-a638-08a079f5b7b5]

617

492 0200 TEL
575 2785 DIRECT

Margolis + Fishman, Inc.
675 Massachusetts Avenue
Cambridge, MA 02139



________________________________
