### ISSUE TITLE
[Bug]: pyrevit Transaction crashes Revit 2024 when canceling occurred failure message

### ISSUE THREAD

**Issue by nodatasheet** [pyrevitlabs/pyRevit#2268]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [x] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

When using `pyrevit.revit.Transaction()` with default failure handling options `swallow_errors=False`, occurred failure crashes Revit 2024 if you press "Cancel" button.

### ⌨ Error/Debug Message

```shell

```

### ♻️ To Reproduce

Open Revit 2024 (any release including latest 2024.2.1 atm ) and create new project.
To provoke the failure message with the code:
1. Create the wall and copy its id
2. Add project length parameter "P" for walls
3. Add the wall to group
4. Copy the group, so you have two group instances
5. Set parameter using code:
```python
from pyrevit import DB, revit

doc = revit.doc
elem = doc.GetElement(DB.ElementId(1594015))  # get wall by id

with revit.Transaction('Set P', doc):
    elem.LookupParameter('P').Set(1)
```
6. Transaction is completed but then appears failure message. If you cancel it, Revit crashes.
  ![image](https://github.com/pyrevitlabs/pyRevit/assets/92411255/d2c5de8f-47d0-4ff9-8e83-bb77de27905d)

### ⏲️ Expected behavior

Pressing cancel on failure message should cancel the transaction.

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Revit 24.2.1 | Version: 24.2.10.64 | Build: 20240408_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"

mypyrevit | Branch: "master" | Version: "4.8.16:13e75bf" | 
pyRevit CLI v4.8.16.24121+2117.23a0b8cbc4babdeb29a0611e159d017bbe9cbad5
```

### Additional context

I don't have 2023 Revit installed, but in 2022 there is no such behavior. Issue occurs in Revit 2024 only.

**Comment by nodatasheet** [comment]
In my opinion this happens because pyRevit Transaction wrapper sets "empty" `FailureHandlingOptions` even if it is not required: [L61](https://github.com/pyrevitlabs/pyRevit/blob/13e75bfcb403d508e1c4e19c9fd0a2f53e8f539c/pyrevitlib/pyrevit/revit/db/transaction.py#L61)

Moving setter inside the `if swallow_errors:` block solves the issue.

**Comment by sanzoghenzo** [comment]
It might be a shot in the dark, but would you please try to add `self._rvtxn.Dispose()` at the very end of the `Transaction.__exit__` method?

I've the impression that we never dispose the Revit Transaction object properly: a [question in the forum](https://discourse.pyrevitlabs.io/t/use-autodesk-imports-with-pyrevit-transaction/3081/7?u=sanzoghenzo) made me analyze the pyrevit Transaction context manager and realize that there's no call to `Dispose` anywhere.

Maaaaaaaayyyyybe the crash could be related to this (I doubt it because it should crash every time, but who knows 😅)

**Comment by nodatasheet** [comment]
@sanzoghenzo you were right 😄 

https://github.com/pyrevitlabs/pyRevit/assets/92411255/0eaaf0cb-6c8c-46d0-beba-59ba0a5c49b1

..so where do we add it? After Commit and all Rollbacks?
```python
def __exit__(self, exception, exception_value, traceback):
    if exception:
        self._rvtxn.RollBack()
        self._rvtxn.Dispose()  # here?
        if self._logerror:
            mlogger.error('Error in Transaction Context. '
                            'Rolling back changes. | %s:%s',
                            exception, exception_value)
    else:
        try:
            self._rvtxn.Commit()
            self._rvtxn.Dispose()  # here
        except Exception as errmsg:
            self._rvtxn.RollBack()
            self._rvtxn.Dispose()  # and here?
            mlogger.error('Error in Transaction Commit. '
                            'Rolling back changes. | %s', errmsg)
```

Another question: what should we do with `TransactionGroup`? It does not have this issue.

And if we set `TransactionGroup.IsFailureHandlingForcedModal` to `False`, Revit does not crash, but only rises exception: 
>The transaction's document is currently in failure mode. Transaction groups cannot be closed until failure handling is finished. You may use a transaction finalizer to close a group after the failure handling ends.

**Comment by sanzoghenzo** [comment]
I would add it at the very end of the `__exit__` method, with the same indentation of `if exception:` and `else:`, so that it is always executed (as it should) and we avoid code duplication.

`TransactionGroup` is an `IDisposable`, too, so yes, we should add the same line at the end of its `__exit__` method.
