### ISSUE TITLE
PyRevit does not work anymore

### ISSUE THREAD

**Issue by salvafari** [pyrevitlabs/pyRevit#2270]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

![Py01](https://github.com/pyrevitlabs/pyRevit/assets/170716488/4e6ce6aa-0e69-4eb3-ae2f-f33de5cf64cc)
![PY_02](https://github.com/pyrevitlabs/pyRevit/assets/170716488/ff354d94-ceef-46d7-9876-8e2ddf6776ec)

### ⌨ Error/Debug Message

```shell
I put the screenshots of the messages
```

### ♻️ To Reproduce

1. start revit 2024
2. the appears the error as the screenshots

### ⏲️ Expected behavior

I expect to open Revit  with Py revit

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Microsoft Windows [Version 10.0.22631.3593]
(c) Microsoft Corporation. All rights reserved.

C:\Users\salvatore>pyrevit env.
Usage: pyrevit COMMAND [OPTIONS]

pyRevit environment and clones manager

    Options:
        -h --help                Show this help
        -V --version             Show version
        --usage                  Print all usage patterns
        --verbose                Print info messages
        --debug                  Print docopt options and logger debug messages
        --log=<log_file>         Output log messages to external log file

    Management Commands:
        env                      Print environment information
        update                   Update remote resources used by this utility
        clones                   Manage pyRevit clones
        extensions               Manage pyRevit extensions
        attached                 Manage pyRevit attachments to installed Revit
        releases                 Info about pyRevit releases
        revits                   Manage installed Revits
        caches                   Manage pyRevit caches
        configs                  Manage pyRevit configurations

    Commands:
        clone                    Create a clone of pyRevit on this machine
        extend                   Create a clone of a third-party pyRevit extension on this machine
        attach                   Attach pyRevit clone to installed Revit
        switch                   Switch active pyRevit clone
        detach                   Detach pyRevit clone from installed Revit
        config                   Configure pyRevit for current user
        run                      Run python script in Revit
        doctor                   Fix potential or real problems

    Help Commands:
        wiki                     Open pyRevit Wiki
        blog                     Open pyRevit blog
        docs                     Open pyRevit docs
        source                   Open pyRevit source repo
        youtube                  Open pyRevit on YouTube
        support                  Open pyRevit support page

Run 'pyrevit COMMAND --help' for more information on a command.
```

### Additional context

Please tell me if you need more informations

**Comment by sanzoghenzo** [comment]
Hi @salvafari, 
Please post the output of the command `pyrevit env` without the final dot, as you can see the output you posted doesn't tell us anything. 

> Please tell me if you need more informations

Indeed we need more info: when you say that it doesn't work _anymore_, do you mean that it worked before? What has changed?
Have you really tried to follow the troubleshooting guide?

/fix-install

**Comment by Michgadu8** [comment]
Hi, I have a similar issue I already did the troubleshooting guide and still does not work, below more details! 

Error shown when I launch Revit any of the versions I have 2022, 2023 and 2024
![error pyrevit](https://github.com/pyrevitlabs/pyRevit/assets/136072516/44b2ae7d-32b8-44f5-b174-d6957cf23610)



C:\Users\MichelleGallegosHaml>pyrevit attach main --installed
Usage: pyrevit COMMAND [OPTIONS]

pyRevit environment and clones manager

    Options:
        -h --help                Show this help
        -V --version             Show version
        --usage                  Print all usage patterns
        --verbose                Print info messages
        --debug                  Print docopt options and logger debug messages
        --log=<log_file>         Output log messages to external log file

    Management Commands:
        env                      Print environment information
        update                   Update remote resources used by this utility
        clones                   Manage pyRevit clones
        extensions               Manage pyRevit extensions
        attached                 Manage pyRevit attachments to installed Revit
        releases                 Info about pyRevit releases
        revits                   Manage installed Revits
        caches                   Manage pyRevit caches
        configs                  Manage pyRevit configurations

    Commands:
        clone                    Create a clone of pyRevit on this machine
        extend                   Create a clone of a third-party pyRevit extension on this machine
        attach                   Attach pyRevit clone to installed Revit
        switch                   Switch active pyRevit clone
        detach                   Detach pyRevit clone from installed Revit
        config                   Configure pyRevit for current user
        run                      Run python script in Revit
        doctor                   Fix potential or real problems

    Help Commands:
        wiki                     Open pyRevit Wiki
        blog                     Open pyRevit blog
        docs                     Open pyRevit docs
        source                   Open pyRevit source repo
        youtube                  Open pyRevit on YouTube
        support                  Open pyRevit support page


C:\Users\MichelleGallegosHaml>help
For more information on a specific command, type HELP command-name
ASSOC          Displays or modifies file extension associations.
ATTRIB         Displays or changes file attributes.
BREAK          Sets or clears extended CTRL+C checking.
BCDEDIT        Sets properties in boot database to control boot loading.
CACLS          Displays or modifies access control lists (ACLs) of files.
CALL           Calls one batch program from another.
CD             Displays the name of or changes the current directory.
CHCP           Displays or sets the active code page number.
CHDIR          Displays the name of or changes the current directory.
CHKDSK         Checks a disk and displays a status report.
CHKNTFS        Displays or modifies the checking of disk at boot time.
CLS            Clears the screen.
CMD            Starts a new instance of the Windows command interpreter.
COLOR          Sets the default console foreground and background colors.
COMP           Compares the contents of two files or sets of files.
COMPACT        Displays or alters the compression of files on NTFS partitions.
CONVERT        Converts FAT volumes to NTFS.  You cannot convert the
               current drive.
COPY           Copies one or more files to another location.
DATE           Displays or sets the date.
DEL            Deletes one or more files.
DIR            Displays a list of files and subdirectories in a directory.
DISKPART       Displays or configures Disk Partition properties.
DOSKEY         Edits command lines, recalls Windows commands, and
               creates macros.
DRIVERQUERY    Displays current device driver status and properties.
ECHO           Displays messages, or turns command echoing on or off.
ENDLOCAL       Ends localization of environment changes in a batch file.
ERASE          Deletes one or more files.
EXIT           Quits the CMD.EXE program (command interpreter).
FC             Compares two files or sets of files, and displays the
               differences between them.
FIND           Searches for a text string in a file or files.
FINDSTR        Searches for strings in files.
FOR            Runs a specified command for each file in a set of files.
FORMAT         Formats a disk for use with Windows.
FSUTIL         Displays or configures the file system properties.
FTYPE          Displays or modifies file types used in file extension
               associations.
GOTO           Directs the Windows command interpreter to a labeled line in
               a batch program.
GPRESULT       Displays Group Policy information for machine or user.
GRAFTABL       Enables Windows to display an extended character set in
               graphics mode.
HELP           Provides Help information for Windows commands.
ICACLS         Display, modify, backup, or restore ACLs for files and
               directories.
IF             Performs conditional processing in batch programs.
LABEL          Creates, changes, or deletes the volume label of a disk.
MD             Creates a directory.
MKDIR          Creates a directory.
MKLINK         Creates Symbolic Links and Hard Links
MODE           Configures a system device.
MORE           Displays output one screen at a time.
MOVE           Moves one or more files from one directory to another
               directory.
OPENFILES      Displays files opened by remote users for a file share.
PATH           Displays or sets a search path for executable files.
PAUSE          Suspends processing of a batch file and displays a message.
POPD           Restores the previous value of the current directory saved by
               PUSHD.
PRINT          Prints a text file.
PROMPT         Changes the Windows command prompt.
PUSHD          Saves the current directory then changes it.
RD             Removes a directory.
RECOVER        Recovers readable information from a bad or defective disk.
REM            Records comments (remarks) in batch files or CONFIG.SYS.
REN            Renames a file or files.
RENAME         Renames a file or files.
REPLACE        Replaces files.
RMDIR          Removes a directory.
ROBOCOPY       Advanced utility to copy files and directory trees
SET            Displays, sets, or removes Windows environment variables.
SETLOCAL       Begins localization of environment changes in a batch file.
SC             Displays or configures services (background processes).
SCHTASKS       Schedules commands and programs to run on a computer.
SHIFT          Shifts the position of replaceable parameters in batch files.
SHUTDOWN       Allows proper local or remote shutdown of machine.
SORT           Sorts input.
START          Starts a separate window to run a specified program or command.
SUBST          Associates a path with a drive letter.
SYSTEMINFO     Displays machine specific properties and configuration.
TASKLIST       Displays all currently running tasks including services.
TASKKILL       Kill or stop a running process or application.
TIME           Displays or sets the system time.
TITLE          Sets the window title for a CMD.EXE session.
TREE           Graphically displays the directory structure of a drive or
               path.
TYPE           Displays the contents of a text file.
VER            Displays the Windows version.
VERIFY         Tells Windows whether to verify that your files are written
               correctly to a disk.
VOL            Displays a disk volume label and serial number.
XCOPY          Copies files and directory trees.
WMIC           Displays WMI information inside interactive command shell.





py revit clones

C:\Users\MichelleGallegosHaml>pyrevit clones
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.16.24121+2117" | Path: "C:\Users\MichelleGallegosHaml\AppData\Roaming\pyRevit-Master"

C:\Users\MichelleGallegosHaml>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.16.24121+2117" | Path: "C:\Users\MichelleGallegosHaml\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "24.2" | Engine: DEFAULT (2711) | Path: "C:\Users\MichelleGallegosHaml\AppData\Roaming\pyRevit-Master"
master | Product: "23.1.4" | Engine: DEFAULT (2711) | Path: "C:\Users\MichelleGallegosHaml\AppData\Roaming\pyRevit-Master"
master | Product: "2022.1.5" | Engine: DEFAULT (2711) | Path: "C:\Users\MichelleGallegosHaml\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\MichelleGallegosHaml\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.4 | Version: 23.1.40.56 | Build: 20240411_0945(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.22631]
Executing User: AzureAD\MichelleGallegosHaml
Active User: AzureAD\MichelleGallegosHaml
Admin Access: No
%APPDATA%: "C:\Users\MichelleGallegosHaml\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.6.2 v4.7 v4.7.1 v4.7.2 v4.8 v4.8.1 v4.X
Installed .Net-Core Target Packs: v8.0.202
pyRevit CLI v4.8.16.24121+2117.23a0b8cbc4babdeb29a0611e159d017bbe9cbad5

C:\Users\MichelleGallegosHaml>

**Comment by sanzoghenzo** [comment]
Hi @Michgadu8 sorry for the waiting...
You typed some commands wrong.
Please follow the troubleshooting guide you'll find at the next post.

/install-fix

**Comment by sanzoghenzo** [comment]
Try these steps:

1. Uninstall pyRevit

2. Delete C:\ProgramData and %AppData%\ pyRevit and pyrevit-master folders
      
3. Move all Revit addins to a temporary location. Usual addins locations include:
         - %AppData%\Autodesk\Revit\Addins<year>
         - %AppData%\Autodesk\ApplicationPlugins
         - %ProgramData%\Autodesk\Revit\Addins<year>
         - %ProgramData%\Autodesk\ApplicationPlugins

4. [Reboot computer]
      
5. Reinstall pyRevit
      
6. Started each version of Revit confirming pyRevit successfully compiled at startup.
      
7. Move all Revit addins that were moved in step 3 back to their original location.
    You may want to add them one at a time and start a revit session everytime to figure out which ones are causing the issue.

**Comment by czwangxtt** [comment]
We see this issue in many computers with the same error. pyRevit doesn't work for any Revit version for our case.

**Comment by deddolo** [comment]
It might be a conflict with another addin. Do you have the Guardian add-in installed?

**Comment by aussieBIMguru** [comment]
At my company the prime culprit for this has been 'Forma for Revit'. It reinstalls with every Revit update and install,  and fries pyRevit out every time (even if uninstalled).

Fix has been for me:
1. Uninstall forma
2. Uninstall pyRevit
3. Delete the pyRevit folders in ProgramData and roaming
4. Reinstall pyRevit
