### ISSUE TITLE
[Bug]:   Make (Model) Pattern maker fail

### ISSUE THREAD

**Issue by Deadheavy** [pyrevitlabs/pyRevit#2272]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

I'm trying to create a hatch pattern w/ Revit 2023.1.

I select the lines (thin lines in this case), click Make Pattern, ensure it has model pattern selected, select the bottom left corner and the top right corner and then I'm kicked back to the Revit interface - no dialog box telling me any error messages, nor that it was successful (I've created hatches before).

### ⌨ Error/Debug Message

```shell
No error messages, or debug messages.
```

### ♻️ To Reproduce

1. Select Lines
2. Click Make Pattern
3. Type in a name, ensure Model is selected (everything is as defaults)
4. Click Create Pattern

### ⏲️ Expected behavior

Dialog box should open up and say something to the effect of "Pattern created"

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.16.24121+2117" | Path: "C:\Users\deadh\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "24.2" | Engine: DEFAULT (2711) | Path: "C:\Users\deadh\AppData\Roaming\pyRevit-Master"
master | Product: "23.1.3" | Engine: DEFAULT (2711) | Path: "C:\Users\deadh\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\deadh\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
==> Running Revit Instances
PID: 11188 | 23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2023"
==> User Environment
Microsoft Windows 10 [Version 10.0.22631]
Executing User: AMP-DESK\deadh
Active User: AMP-DESK\deadh
Admin Access: No
%APPDATA%: "C:\Users\deadh\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.16.24121+2117.23a0b8cbc4babdeb29a0611e159d017bbe9cbad5
```

**Comment by jmcouffin** [comment]
You have tried restarting  both computer and Revit?

**Comment by Deadheavy** [comment]
It's been a problem that has existed for a while, multiple reboots and restarts have occurred.

**Comment by jmcouffin** [comment]
Can you provide a rvt file with the lines you used to create the pattern so that I can reproduce? @Deadheavy

**Comment by Deadheavy** [comment]
I just upgraded to Revit 23.1.40.56 and the issue has gone away.  You can close this ticket.  thanks @jmcouffin
