### ISSUE TITLE
[Bug]: Color Splasher

### ISSUE THREAD

**Issue by GianClaudioScarafini** [pyrevitlabs/pyRevit#2280]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [x] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

when I am trying to use  "create View filter" there is no creation of the filter. 

I am using this version:
![image](https://github.com/pyrevitlabs/pyRevit/assets/77918123/36c108fc-8963-4392-9427-88e7c1b274c5)

I have tested it on different Revit versions: 2022, 2023, and 2024.

Additionally, to ensure it is not related to the view having a view template, I set the value to "none."

### ⌨ Error/Debug Message

I have not received any error msg 

if I use the debug code I can see this:
![image](https://github.com/pyrevitlabs/pyRevit/assets/77918123/a6e5fc1f-f791-49cb-9b1f-55bf0f0d4950)

### ♻️ To Reproduce

select a 3D views 
click on pyrevit
got to "color spasher"  and click 
select "family and type"
random colors 
create View filter 
and not be able to see any filter

### ⏲️ Expected behavior

I should be able to see the list of filters 

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.9 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2019.2.6 | Version: 19.2.60.3 | Build: 20220224_1700(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019\"
==> Running Revit Instances
PID: 11000 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
PID: 16576 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
PID: 19328 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
PID: 5848 | 23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2023"
PID: 18440 | 23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2023"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: HTL\gian.scarafini
Active User: HTL\gian.scarafini
Admin Access: No
%APPDATA%: "C:\Users\gian.scarafini\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.16.24121+2117.23a0b8cbc4babdeb29a0611e159d017bbe9cbad5
```

**Comment by GianClaudioScarafini** [comment]
also, I am not sure why when I click on "reset all color" all the elements remain with the same color and I can go back...


thank you for your time :) I appreciate it

**Comment by jmcouffin** [comment]
You cannot create filters for 'family and types in view filters in the UI, therefore, the API command does not make it available either

**Comment by jmcouffin** [comment]
We should handle these types of exception. But it is not the case yet.

**Comment by chauhuh** [comment]
I tried creating view filters for several different parameters including ones I know that I can manually create a filter for and it errored out. The error I receive is 'FormCats' object has no attribute '_listBox2'.

I can also replicate the Reset all Color error not functioning. No error message given.

**Comment by jmcouffin** [comment]
@GianClaudioScarafini 
- filters cannot be created for **family and type** as the parameter is not exposed in the revit API for filter creation

**Comment by jmcouffin** [comment]
> I tried creating view filters for several different parameters including ones I know that I can manually create a filter for and it errored out. The error I receive is 'FormCats' object has no attribute '_listBox2'.
> 
> I can also replicate the Reset all Color error not functioning. No error message given.

Please open a different issue
