### ISSUE TITLE
[Bug]: PyRevitLoader - Error Loading pyRevit

### ISSUE THREAD

**Issue by BeardBishwo** [pyrevitlabs/pyRevit#2292]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

PyRevitLoader - Error Loading pyRevit

### ⌨ Error/Debug Message

```shell
PyRevitLoader - Error Loading pyRevit
```

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
System.TypeLoadException: Could not load type
x
'System.Runtime.Remoting.RemotingServices' from assembly
'mscorlib, Version=4.0.0.0, Culture—neutral,
at
Microsoft.Scripting.Hosting.Providers.HostingHelpers.CreateSc...
engine, Scope scope)
at IronPython.Hosting.PythonService.CreateModule(String
name, String filename, String docString)
at IronPython.Hosting.Python.CreateModule(ScriptEngine
engine, String name)
at
PyRevitLoader.ScriptExecutor.SetupEnvironment(ScriptEngine
engine)
at PyRevitLoader.ScriptExecutor.ExecuteScript(String
sourcePath, IEnumerable*1 sysPaths, String logFilePath,
IDictionary*2 variables)
Close
```

![image](https://github.com/pyrevitlabs/pyRevit/assets/174262221/e561b5b4-b583-419e-8391-4f4cc46b043a)

**Comment by FrancoTonutti** [comment]
Are you using Revit 2025? Unfortunately, pyrevit does not work with this version yet. https://github.com/pyrevitlabs/pyRevit/pull/2088 https://github.com/pyrevitlabs/pyRevit/pull/2190

**Comment by BeardBishwo** [comment]
> Are you using Revit 2025? Unfortunately, pyrevit does not work with this version yet. #2088 #2190

when it will be available for 2025

**Comment by martinservold** [comment]
Nevermind. I reinstalled the 'beta' branch again and it worked fine the second time. (must have been pathed to the older version still somehow even though I triple checked it).
