### ISSUE TITLE
I'm having problem with Revit 2024 pyrevit loader

### ISSUE THREAD

**Issue by danielraziel** [pyrevitlabs/pyRevit#2301]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Hi, I have tried many ways described in issues, like #1075 and still it doesn't work. tried reinstalling both revit and pyrevit and ironpython. using without ironpyton, with ironpython, different versions of it (2.7.11 2.7.12 3.4.1) but the loader still has the famous (ironpython traceback issue)
I don't know how to fix it... can anyone help please?

![image](https://github.com/pyrevitlabs/pyRevit/assets/37154394/945ba7eb-f035-49aa-b09c-342b0d0da936)
![image](https://github.com/pyrevitlabs/pyRevit/assets/37154394/9991008a-7d1c-426f-b38c-b5f7533ce2ce)

### ⌨ Error/Debug Message

```shell
C:\Users\Danial>pyrevit attached
==> Attachments
master | Product: "2024 First Customer Ship" | Engine: DEFAULT (2711) | Path: "C:\Users\Danial\AppData\Roaming\pyRevit-Master"
```

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
C:\Users\Danial>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.16.24121+2117" | Path: "C:\Users\Danial\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "2024 First Customer Ship" | Engine: DEFAULT (2711) | Path: "C:\Users\Danial\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Danial\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2024 First Customer Ship | Version: 24.0.4.427 | Build: 20230308_1635(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
==> Running Revit Instances
PID: 1880 | 2024 First Customer Ship | Version: 24.0.4.427 | Build: 20230308_1635(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: DESKTOP-T1P8LO0\Danial
Active User: DESKTOP-T1P8LO0\Danial
Admin Access: No
%APPDATA%: "C:\Users\Danial\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.16.24121+2117.23a0b8cbc4babdeb29a0611e159d017bbe9cbad5
```

**Comment by GianClaudioScarafini** [comment]
I have the same issue with this version:
 24.2.10.64

**Comment by jmcouffin** [comment]
both errors are different from #1075 
For the first one @danielraziel, 
use these steps:

**Comment by danielraziel** [comment]
> both errors are different from #1075 For the first one @danielraziel, use these steps:

Thanks a lot!! I'll try it and post the result here tomorrow.

**Comment by danielraziel** [comment]
> /install-fix
I have moved all of the folders that were mentioned in the guide to another location in desktop, then reboot reinstalled and I still get the same error I believe...

![image](https://github.com/pyrevitlabs/pyRevit/assets/37154394/83f69039-6ddf-46a7-8022-6a617be7dfd1)

**Comment by danielraziel** [comment]
> maybe this is the issue: https://stackoverflow.com/a/65111729/20894305 Or this https://www.epiusers.help/t/error-when-launching-the-image-data-generated-an-overflow-during-processing/104872/3

WOW! Thanks  a lot!! it fixed my problem! my display color was different from default!
many thanks dear @jmcouffin u r a hero!

**Comment by jmcouffin** [comment]
Hero I don't know, but glad it helped!

**Comment by jmcouffin** [comment]
> I have similar issue with this version: 24.2.10.64
> 
> ![image](https://private-user-images.githubusercontent.com/77918123/345050440-0085226a-b880-4345-bb03-f19c59ba46c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjkzMDksIm5iZiI6MTcyMDE2OTAwOSwicGF0aCI6Ii83NzkxODEyMy8zNDUwNTA0NDAtMDA4NTIyNmEtYjg4MC00MzQ1LWJiMDMtZjE5YzU5YmE0NmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA4NDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZmIyNDk1Mzg0ZjU0N2IxMDlhNjUxYTQ3NTMyZThjOGI5YmM4NDg4N2Q4Zjc3YTQzYjg1Mzg1MTk4ZTJjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GoNMZGEgUXsVGMstmSi1LrlKRb7bRbJrPD0M01XJRUc)

@GianClaudioScarafini 
you issue is different but this fix should do the job:
https://github.com/pyrevitlabs/pyRevit/issues/2301#issuecomment-2203530155
If not, please open a new issue

**Comment by welcomemavangamanzambi-eng** [comment]
> > Peut-être que c’est là le problème : https://stackoverflow.com/a/65111729/20894305 Ou ce https://www.epiusers.help/t/error-when-launching-the-image-data-generated-an-overflow-during-processing/104872/3
> 
> WAOUH ! Merci beaucoup !! Ça a résolu mon problème ! La couleur de mon écran était différente de celle par défaut ! Merci beaucoup ma chère, tu es un héros !

chez moi ça ne marche pas
