### ISSUE TITLE
[Bug]: Revit 2025 pyRevit 

### ISSUE THREAD

**Issue by AhmedAlgainy** [pyrevitlabs/pyRevit#2310]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

not loaded pyrevit on revit 2025 and showing this message as image 
<img width="421" alt="Screenshot 2024-07-12 223855" src="https://github.com/user-attachments/assets/2e37671e-4c96-4c56-82af-a873b3714c60">

### ⌨ Error/Debug Message

```shell
in revit 2024 it work normally
```

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.17.24189+1111-wip" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2025" | Engine: DEFAULT (2711) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "24.1" | Engine: DEFAULT (2711) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2023.0.1" | Engine: DEFAULT (2711) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\ahmed\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2025 | Version: 25.0.2.419 | Build: 20240307_1300(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2025\"
24.1 | Version: 24.1.0.66 | Build: 20230701_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
2023.0.1 | Version: 23.0.10.18 | Build: 20220429_1500(x64) | Language: 1033 | Path: "Revit 2023\"
==> Running Revit Instances
PID: 10204 | Autodesk Revit 2025 | Version: 25.0.2.419 | Build: 20240307_1300(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2025"
==> User Environment
Microsoft Windows 10 [Version 10.0.22631]
Executing User: AHMED\ahmed
Active User: Ahmed\ahmed
Admin Access: Yes
%APPDATA%: "C:\Users\ahmed\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
Installed .Net-Core Target Packs: v8.0.102 v8.0.105 v8.0.106 v8.0.107
pyRevit CLI v4.8.17.24189+1111-wip.cb2988da8b37de529462f7986460aa9d963667a5
```

**Comment by sanzoghenzo** [comment]
Pyrevit doesn’t support revit 2025 yet.
Please use a search engine or the githib search feature before opening an issue, you will see that there already are discussions on the topic.
A PR is on the way, it still needs some refinement, but we can't provide any ETA

**Comment by AhmedAlgainy** [comment]
Pyrevit doesn’t support revit 2025 yet ... oh 
Thank you for this information
