### ISSUE TITLE
[Bug]: Error Loading PyRevit - Revit 2025.2

### ISSUE THREAD

**Issue by Halanesi** [pyrevitlabs/pyRevit#2320]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

![PYrevit Error](https://github.com/user-attachments/assets/448ceab5-7344-44b0-8103-aa9039a87d3a)
PYrevit Can't be loaded into Revit 2025

### ⌨ Error/Debug Message

```shell
Error loading PyRevit
```

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
AMD Ryzen 9 5900HX
64gb RAM
Nvidia RTX 3070
Windows11 Home 23H2
Revit 2025.2
```

**Comment by sanzoghenzo** [comment]
Please, search the issues and the forum before posting an issue.
Revit 2025 is still not  supported.

**Comment by Halanesi** [comment]
sorry dear, my mistake
