### ISSUE TITLE
[Bug]: Error: Can not find commit with hash "22c171a496f5985f06ff6934ffee2d7139834e66"

### ISSUE THREAD

**Issue by GHiarsixty** [pyrevitlabs/pyRevit#2329]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Attempting to use commit:  22c171a496f5985f06ff6934ffee2d7139834e66
Sequence is:
pyrevit clone TESTCLONENAME --dest="C:\pyRevit"
pyrevit clones commit TESTCLONENAME 22c171a496f5985f06ff6934ffee2d7139834e66

Get an error:  Error: Can not find commit with hash "22c171a496f5985f06ff6934ffee2d7139834e66"
I can use other commits successfully (such as 7b1ebab28758ff14f90191f56987d307cdf47e14).  And I thought I had this working two weeks ago for the "v4.8.16.24121+2117" commit , but today, not working.

I have also tried using the tag and it does resolve to the commit, but has the same error.
pyrevit clones version TESTCLONENAME "v4.8.16.24121+2117"
Error: Can not find commit with hash "22c171a496f5985f06ff6934ffee2d7139834e66"

### ⌨ Error/Debug Message

```shell
Error: Can not find commit with hash "22c171a496f5985f06ff6934ffee2d7139834e66"

Debug: Valid pyRevit clone "C:\pyRevit\TESTCLONENAME"
Debug: Searching for commit "22c171a496f5985f06ff6934ffee2d7139834e66"...
Error: Can not find commit with hash "22c171a496f5985f06ff6934ffee2d7139834e66" (pyRevitLabs.Common.PyRevitException)
   at pyRevitLabs.Common.GitInstaller.RebaseToCommit(String repoPath, String commitHash)
   at pyRevitCLI.PyRevitCLICloneCmds.GetSetCloneCommit(String cloneName, String commitHash)
   at pyRevitCLI.PyRevitCLI.ProcessArguments()
   at pyRevitCLI.PyRevitCLI.Main(String[] args)
```

### ♻️ To Reproduce

Install CLI
From Command prompt:
pyrevit clone TESTCLONENAME --dest="C:\pyRevit"
pyrevit clones commit TESTCLONENAME 22c171a496f5985f06ff6934ffee2d7139834e66

### ⏲️ Expected behavior

"pyrevit clones commit" command should complete without error and result in commit 22c171a496f5985f06ff6934ffee2d7139834e66

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
I've subbed out the real username:

==> Registered Clones (full git repos)
TESTCLONENAME | Branch: "master" | Version: "4.8.16:f9fa0d2" | Path: "C:\pyRevit\TESTCLONENAME"
==> Registered Clones (deployed from archive/image)
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\TESTUSER\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.4 | Version: 22.1.40.58 | Build: 20230505_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.8 | Version: 21.1.80.35 | Build: 20230515_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: DOMAINNAME\TESTUSER
Active User:
Admin Access: Yes
%APPDATA%: "C:\Users\TESTUSER\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.16.24121+2117.23a0b8cbc4babdeb29a0611e159d017bbe9cbad5
```

**Comment by jmcouffin** [comment]
Hi @GHiarsixty 
I suppose this has to do with the fact that one is on the master branch and the other on the develop-4 one.
You may have to switch branch first and then query the commit of the develop-4 branch.

**Comment by sanzoghenzo** [comment]
`pyrevit clones commit` doesn't check for updates, you have to run `pyrevit clones update TESTCLONENAME` first (or use git pull directly)

**Comment by sanzoghenzo** [comment]
Can we close this?
