### ISSUE TITLE
[Bug]: Revit 2025 WIP - Critical error shown when opening Revit for ">>>" slideout in YAML file

### ISSUE THREAD

**Issue by acco-jpitts** [pyrevitlabs/pyRevit#2350]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Opening Revit displays an error ```Error creating item: <type_id '>>>' name 'None' @ 'None'> | '_PyRevitRibbonGroupItem' object has no attribute 'add_slideout'``` 

This appears to be from my own extension not from pyRevit ribbon, but all of my slideout panels are working fine so it seems to be a false positive. I have seen this on previous pyRevit-4 versions as well, although it was only when installing using WIP installers I think. Using master branch or latest available develop-4 installers did not cause this issue

For the master branch and develop-4 installers I use the CLI to install to ```C:\pyRevit-Master``` and the WIP installers I do not use the CLI and pyRevit installs to ```C:\Program Files\pyRevit-Master```. Either way, my extension still installs to the same ```C:\pyRevit-Master\extensions```

![2024-08-15_07-14-49](https://github.com/user-attachments/assets/271b7149-67ed-4dfa-8279-d3e56f0cdd7a)

### ⌨ Error/Debug Message

```shell
[pyrevit.loader.uimaker] Error creating item: <type_id '>>>' name 'None' @ 'None'> | '_PyRevitRibbonGroupItem' object has no attribute 'add_slideout'
```

### ♻️ To Reproduce

Open Revit with extension that uses slideout panel

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
C:\Users\XXXXX>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "5.0.0.24227+1428-wip" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2025" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "24.2" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "23.1.3" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2022.1.5" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2021.1.9" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2020.2.9" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
XXXXXX | Type: UIExtension | Repo: "https://github.com/XXXXXX/XXXXXXXXX.git" | Installed: "C:\pyRevit-Master\extensions\XXXXXXX"
==> Default Extension Search Path
C:\Users\XXXXX\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\pyRevit-Master\extensions
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2025 | Version: 25.0.2.419 | Build: 20240307_1300(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2025\"
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.9 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 30240 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
PID: 17860 | 2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2022"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: XXXXXXX
Error: Could not load file or assembly 'System.Management, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Run with "--debug" option to see debug messages
```

### Additional context

I have 4 slideout panels in use in my extension. Here is an example of one of the YAML files including a slideout panel. Everything appears functional despite the error.
```  
layout:
  - Ribbon Update
  - ">>>"
  - Toggle
  - ProjectSetup
  - System Flow To None
  - Reload Dynamo Engine
  ```

**Comment by jmcouffin** [comment]
@acco-jpitts why the quotes around the >>>?
I don't think it is required

**Comment by acco-jpitts** [comment]
> @acco-jpitts why the quotes around the >>>? I don't think it is required

![image](https://github.com/user-attachments/assets/e01ef53c-d97b-45a4-b845-a452c395736f)

**Comment by acco-jpitts** [comment]
actually I just noticed just above on that same page it shows example without the quotes....

![image](https://github.com/user-attachments/assets/0f797be6-56f8-44ef-b72f-e2d959883488)

[Link](https://pyrevitlabs.notion.site/Bundle-Layout-39f1491439d44343896fe0adc4270129)

I have always used the quotes and this hasn't happened except when using WIP builds (I think)

**Comment by jmcouffin** [comment]
Yeah, 
I have used it scarcely but without quotes....
I will check tomorrow

**Comment by sanzoghenzo** [comment]
Quotes are ok, in fact the error correctly states `'>>>'` with single quotes, so the double quotes are correctly parsed (in yaml format quotes/double quotes are optional when the value is clearly a text)

My guess is that the add_slideout should be called on the parent item and not the `>>>` element, and some .net8 library changed it behavior... but it's just a guess!

**Comment by jmcouffin** [comment]
The slide out works after a restart of Revit.
both `">>>"` and `">>>>>"` like in the pyrevit tools slideout

**Comment by jmcouffin** [comment]
@acco-jpitts do you still have the bug?

**Comment by acco-jpitts** [comment]
@jmcouffin No I do not and I believe it was caused by typos in translations that have already been corrected.
