### ISSUE TITLE
[Bug]: Pick file/folder form fills screen, not resizeable (pyRevit5)

### ISSUE THREAD

**Issue by aussieBIMguru** [pyrevitlabs/pyRevit#2354]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

It looks like any form for picking files and folders no longer sizes itself properly, and fills the screen. This is still workable for now, but seems to affect all versions vs just Revit 2025.

### ⌨ Error/Debug Message

```shell
No error/debug message - UI/UX related.
```

### ♻️ To Reproduce

1. Use a pick file or folder form
2. The dialogue will fill the full window
3. Window does not seem resizeable by user also

### ⏲️ Expected behavior

Form is a more standard size by default, user can resize/move the window.

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "5.0.0.24227+1428-wip" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2025" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "24.2.1" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "23.1.5" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2022.1.5" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2021.1.10" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2020.2.9" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
Panel | Type: Unknown | Repo: "" | Installed: "C:\Users\gavin.crump\OneDrive - Architectus\Documents\GitHub\pyRarch\Toolbar\Panel.extension"
==> Default Extension Search Path
C:\Users\gavin.crump\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\gavin.crump\OneDrive - Architectus\Documents\GitHub\pyRarch\Toolbar
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2025 | Version: 25.0.2.419 | Build: 20240307_1300(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2025\"
24.2.1 | Version: 24.2.10.64 | Build: 20240408_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.5 | Version: 23.1.50.23 | Build: 20240709_1030(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.10 | Version: 21.1.100.12 | Build: 20240319_1700(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 27756 | 23.1.5 | Version: 23.1.50.23 | Build: 20240709_1030(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2023"
==> User Environment
Microsoft Windows 10 [Version 10.0.22631]
Executing User: ARCHITECTUS\gavin.crump
Active User: ARCHITECTUS\gavin.crump
Admin Access: No
%APPDATA%: "C:\Users\gavin.crump\AppData\Roaming"
Latest Installed .Net Framework: 8.0.0
Installed .Net Target Packs: v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7.2 v4.8 v4.X
Installed .Net-Core Target Packs: v6.0.401
pyRevit CLI v5.0.0.24227+1428-wip.807907d3acc8f7b165dfff1e8c766581185ee86b
```

### Additional context

![image](https://github.com/user-attachments/assets/061c9201-bfd9-448b-9278-1f64ac619959)

**Comment by jmcouffin** [comment]
I checked and cannot reproduce on any revit version.
I will keep this issue opened and see if someone else has the same issue
I am on windows 10 too.
When you just grab the top bar and move the window or try the resizing handle at the bottom right it does not react?

**Comment by dosymep** [comment]
@jmcouffin maybe we have problem with lib `Microsoft.WindowsAPICodePack.Shell.dll`

**Comment by jmcouffin** [comment]
> @jmcouffin maybe we have problem with lib `Microsoft.WindowsAPICodePack.Shell.dll`

not so sure, I cannot reproduce and my setup is very similar @dosymep

**Comment by aussieBIMguru** [comment]
Apologies team, this seems to have been related to the windows update that made default windows full screen until double clicked at the top bar. The restore directory feature was remembering this until I fixed one and ran a tool.

Closed, thanks for the commentary though!
