### ISSUE TITLE
[Bug]: "Find Unused Keynotes" and "Open Keynotes File" are missing in bundle.yaml

### ISSUE THREAD

**Issue by Thomas84** [pyrevitlabs/pyRevit#2360]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

"Find Unused Keynotes" and "Open Keynotes File" tools are missing in the toolbar, because they are not listed in [bundle.yaml of the Legends.pulldown. ](https://github.com/pyrevitlabs/pyRevit/blob/develop/extensions/pyRevitTools.extension/pyRevit.tab/Drawing%20Set.panel/views.stack/Legends.pulldown/bundle.yaml)
Is this on purpose or should the tools be added to the bundle.yaml?
![image](https://github.com/user-attachments/assets/aa6bc516-ddda-48f1-94e2-ce73c5158024)

### ⌨ Error/Debug Message

```shell
above
```

### ♻️ To Reproduce

1. click on pyRevit 
2. Legends
3. "Find Unused Keynotes" and "Open Keynotes File" tools are missing
4. After Adding the tools the bundle.yaml they appear

### ⏲️ Expected behavior

tools appear

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.16.24121+2117" | Path: "C:\Users\thommy\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2025" | Engine: DEFAULT (2711) | Path: "C:\Users\thommy\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2024" | Engine: DEFAULT (2711) | Path: "C:\Users\thommy\AppData\Roaming\pyRevit-Master"
==> Installed Revits
Autodesk Revit 2025 | Version: 25.1.0.44 | Build: 20240516_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2025\"
Autodesk Revit 2024 | Version: 24.2.10.64 | Build: 20240408_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
```

**Comment by jmcouffin** [comment]
A mistake for sure. Good catch.
Willst Du ein PR machen? @Thomas84

**Comment by Thomas84** [comment]
ja ich bin sowieso gerade noch an den Übersetzungsdateien dran, dann integriere ich es

**Comment by Thomas84** [comment]
the fix is included in https://github.com/pyrevitlabs/pyRevit/pull/2361
