### ISSUE TITLE
[Bug]: Revit Crash Before Splash Screen

### ISSUE THREAD

**Issue by aclavijo1129** [pyrevitlabs/pyRevit#2369]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

After downloading pyRevit 4.8.16.24121 I am unable to open any version of Revit. When I try and open Revit it crashes before the splash screen. I have attempted any solution I could find in the pyRevit Forum and troubleshooting guide and have had no luck getting the program to work.

### ⌨ Error/Debug Message

```shell
N/A
```

### ♻️ To Reproduce

N/A

### ⏲️ Expected behavior

N/A

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
N/A
```

### Additional context

N/A

**Comment by jmcouffin** [comment]
Can you try deactivating all add-ons except pyrevit? Use the diroots app manager for that.

**Comment by aclavijo1129** [comment]
I have tried that and I am still having the same issue. I have also tried to manually disable the other add-ons with still no luck.

**Comment by jmcouffin** [comment]
and uninstalling pyrevit restores the normal loading of Revit?

**Comment by aclavijo1129** [comment]
Yes.

**Comment by jmcouffin** [comment]
- Can you uninstall pyrevit
- disable all remaining addins 
- install pyrevit
- launch revit
- eventually activate back the addins

**Comment by aclavijo1129** [comment]
Unfortunately still having the same issue.

**Comment by aclavijo1129** [comment]
Any other possible solutions?

**Comment by jmcouffin** [comment]
What's your hardware and software setup?
Do you have antivirus, vpn, cyber sec software, firewall of any sort?
To me, if none of the above worked, it is a security or network software or hardware issue

**Comment by jmcouffin** [comment]
Did you find a solution you could share?
