### ISSUE TITLE
[Bug]: python312.dll not found [admin installer]

### ISSUE THREAD

**Issue by Thomas84** [pyrevitlabs/pyRevit#2385]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Our IT has tried to install the latest pyRevit 5 admin WIP. We tested it on 2 Computer and got different Error messages. PyRevit didn't load. 

![image](https://github.com/user-attachments/assets/69967ce3-cdb8-46b3-8c4c-6eaa43aacb2f)

![Bild](https://github.com/user-attachments/assets/b4bfb63a-f095-4be2-855b-e221b05e286d)

### ⌨ Error/Debug Message

```shell
First PC:
IOError: [Errno 2] Ein Teil des Pfades "C:\Program Files\pyRevit-Master\CPY2123\python312.dll" konnte nicht gefunden werden.

Second PC:
TypeError: sequence item 10: expected string, NoneType found
```

### ⏲️ Expected behavior

-

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
first PC: Win11 (pyRevit was never installed)
second PC: WIn10 (pyRevit 4.8.16 was uninstalled before installation)
```

**Comment by jmcouffin** [comment]
please specify which WIP installer version was used.

**Comment by Thomas84** [comment]
![image](https://github.com/user-attachments/assets/4d3635c2-4f85-4e0a-8268-f615911a815c)
I don't know how to identify the exact build, because all WIP files looking similar. Maybe the screenshot helps? It was build on 27.08.2024 23:19 ?

**Comment by jmcouffin** [comment]
It should be this one then
https://github.com/pyrevitlabs/pyRevit/actions/runs/10587136661

so it seems it is mostly an issue with the admin installer.

**Comment by jmcouffin** [comment]
can you try with the non admin one for the sake of the argument @Thomas84

**Comment by Thomas84** [comment]
I have tested the non admin installer of the same WIP version and got this error (pyRevit didn't load):
![image](https://github.com/user-attachments/assets/6be5545d-e7a8-4405-b998-d270ba47edad)

**Comment by sanzoghenzo** [comment]
The "sequence item 10" error is because of the bug introduced with #2374 and that should be solved by #2384 .

The admin installer error should be investigated further

**Comment by Thomas84** [comment]
I download this one: https://github.com/pyrevitlabs/pyRevit/actions/runs/10612084392 and we will test the admin installer on my PC, to see if I get the same error message as the other computer

**Comment by jmcouffin** [comment]
> I download this one: https://github.com/pyrevitlabs/pyRevit/actions/runs/10612084392 and we will test the admin installer on my PC, to see if I get the same error message as the other computer. Or do I need to wait for a new build?

wait and give us a minute (or a week ;p)

**Comment by Thomas84** [comment]
and a quick other question: If someone installs pyRevit5 admin, should the installer uninstall old pyRevit automatically or has it to be done manually before the installation of pyRevit5 ?

**Comment by jmcouffin** [comment]
> and a quick other question: If someone installs pyRevit5 admin, should the installer uninstall the old pyRevit files automatically or has it to be done manually before the installation of pyRevit5 ?

It needs to be handled manually -windows - unsintall- beforehand

**Comment by sanzoghenzo** [comment]
@Thomas84 is it still the case with the latest WIP installer?

**Comment by sanzoghenzo** [comment]
I'm closing this since the "sequence item 10" error is solved, and the first error is likely due to a conflict with previous non-admin user installation (pyrevit installed in users AppData that looks for a dll in C:\Program Files).
