### ISSUE TITLE
[Bug]: Duplicate engines in Active Engine dropdown in Settings + Update Revit versions

### ISSUE THREAD

**Issue by sanzoghenzo** [pyrevitlabs/pyRevit#2389]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

A picure is worth more than a thousand words:

![image](https://github.com/user-attachments/assets/055d7e30-15d5-4ec1-8a8a-c2ffafc51622)

This is because we duplicate the engines for .net core and .net framework, but in the interface we should list them only once.

### ⌨ Error/Debug Message

```shell
see picture
```

### ♻️ To Reproduce

1. Open pyrevit 5 settings
2. Click on the "Active engine" dropdown

### ⏲️ Expected behavior

Engines are listed only once

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
pyRevit 5 WIP, the rest doesn't matter.
```

**Comment by sanzoghenzo** [comment]
Also, the settings UI is missing the last revit version

![image](https://github.com/user-attachments/assets/13fd6f1c-38b1-45f9-97d4-011f7de60f45)

**Comment by jmcouffin** [comment]
> Also, the settings UI is missing the last revit version
> 
> ![image](https://private-user-images.githubusercontent.com/977953/364768252-13fd6f1c-38b1-45f9-97d4-011f7de60f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTg1OTgsIm5iZiI6MTcyNTYxODI5OCwicGF0aCI6Ii85Nzc5NTMvMzY0NzY4MjUyLTEzZmQ2ZjFjLTM4YjEtNDVmOS05N2Q0LTAxMWY3ZGU2MGY0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxMDI0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWVkMGU5MjNjNDY5MjVmYjQzNjk5MjA2YWUxZmFlYmZlNjA2ZTg0YTViZmVlN2NlODE1Mzc3ZDBmNzcwM2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kk3kZD5SptaKjPvFWjNSBPG0BmjP3T5EQeyf5MICIQY)

manual fix in @2384 PR
The automation of this part should be addressed later as it is not urgent
