### ISSUE TITLE
[Bug]: Not able to run PyRevit on Revit 2025?

### ISSUE THREAD

**Issue by theoboze** [pyrevitlabs/pyRevit#2391]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [x] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

![Screenshot 2024-09-07 100744](https://github.com/user-attachments/assets/e4b47d12-690e-4b26-8b12-f5cd4f21b1e2)
Hello, I don't understand what this error message is telling me. This appears after downloading the plugin, prior to any project opening. I recently upgraded from Revit 2024 to 2025, and PyRevit works on the 2024 version, but this message pops up on the 2025 version. Let me know, thanks!

### ⌨ Error/Debug Message

```shell
See image attached in description
```

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
C:\Users\Theo>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.16.24121+2117" | Path: "C:\Users\Theo\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2025" | Engine: DEFAULT (2711) | Path: "C:\Users\Theo\AppData\Roaming\pyRevit-Master"
master | Product: "24.2.1" | Engine: DEFAULT (2711) | Path: "C:\Users\Theo\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Theo\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2025 | Version: 25.0.2.419 | Build: 20240307_1300(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2025\"
24.2.1 | Version: 24.2.10.64 | Build: 20240408_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages

C:\Users\Theo>
```

**Comment by sanzoghenzo** [comment]
Hi @theoboze,
Unfortunately pyRevit is still not compatible with revit 2025.

2025 support will ship with pyrevit version 5, as soon as it is ready. Check this issue #2087 and the forum for more info.
