### ISSUE TITLE
[Bug]:+Manage Keynotes crashing models in Revit 2024

### ISSUE THREAD

**Issue by xtinaleigh** [pyrevitlabs/pyRevit#2393]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Hello! I am having the same issues as users fearonis + lynsaya1982 with Keynote Manager. It happens when my user edits a keynote (keynote file hosted locally on our server) with the pyRevit keynote manager and someone else has added one without syncing. This is occurring when more than one person is editing the keynote files. When he's finished editing the keynote in KM, Revit states he now owns the element but the file is out of date and then immediately runs into the fatal error: "Revit has experienced a fatal error and cannot continue." Revit model is hosted on BIM360. 

### ⌨ Error/Debug Message

```shell
Is Revit considering the keynote file itself an element?
```

### ♻️ To Reproduce

Create a server hosted keynote file linked into a BIM360 Revit project (unsure if this is relevant but this is our current situation). Have more than one person edit keynotes through the keynote manager before syncing with central.

### ⏲️ Expected behavior

Element will be out of date error + fatal error will appear + Revit crash.

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.13.23182+2215" | Path: "C:\Users\rburnett\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2024" | Engine: IPY277 (277) | Path: "C:\Users\rburnett\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\rburnett\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.0" | Engine: IPY277 (277) | Path: "C:\Users\rburnett\AppData\Roaming\pyRevit-Master"
master | Product: "2018.3.3 Security Fix" | Engine: IPY277 (277) | Path: "C:\Users\rburnett\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
TacoBar | Type: Unknown | Repo: "" | Installed: "\\wps1\USER_PROGRAM\pyRevit\TACO Bar\TacoBar.extension"
==> Default Extension Search Path
C:\Users\rburnett\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
\\wps1\USER_PROGRAM\pyRevit\TACO Bar
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2024 | Version: 24.2.10.64 | Build: 20240408_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
Autodesk Revit 2022 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2020.2.0 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
2018.3.3 Security Fix | Version: 18.3.3.18 | Build: 20190510_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2018\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

### Additional context

Version of Revit: Revit 2024.2.1
Version of pyRevit: pyRevit v4.8.13
Keynote file hosting? ACC, BIM360, Server, Gdrive, Sharepoint?: Keynote file hosted on local server
Sync method of the keynote file: Unsure how to check this. Please send additional information.
Error Message / screen capt/text
![fatal error](https://github.com/user-attachments/assets/8caee373-1173-470a-aff2-6ee1c54de4ad)
Journal file
[journal.0221.txt](https://github.com/user-attachments/files/16936173/journal.0221.txt)

**Comment by prajwalbkumar** [comment]
Same goes for Revit 2023 version!

**Comment by jmcouffin** [comment]
duplicate #2388
