### ISSUE TITLE
[Bug]: Latest PyRevit does not work on Revit R22 and R24

### ISSUE THREAD

**Issue by Pietieklipkop** [pyrevitlabs/pyRevit#2394]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

When I open Revit R22, it produces this error stack stating that PyRevit is missing, after I have installed and Reinstalled PyRevit.
The same happens when I open R24, however when I open R25 it detects PyRevit and works.
![WhatsApp Image 2024-09-10 at 08 43 27_b2f78f8a](https://github.com/user-attachments/assets/1b41d520-41d0-4d87-9311-732931797682)
![WhatsApp Image 2024-09-10 at 08 42 14_b0cdfb06](https://github.com/user-attachments/assets/0db52b84-a9f3-4b94-8d81-1ebd2086ce63)

### ⌨ Error/Debug Message

```shell
I am guessing it has something to do with the new framework?
```

### ♻️ To Reproduce

1. install latest PyRevit
2. Open Revit R22 or R24

### ⏲️ Expected behavior

The expected behavior is that PyRevit works normally when I open Revit R22

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
C:\Users\loure>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "5.0.0.24246+1410-wip" | Path: "C:\Users\loure\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2025" | Engine: DEFAULT (2712) | Path: "C:\Users\loure\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2024" | Engine: DEFAULT (2712) | Path: "C:\Users\loure\AppData\Roaming\pyRevit-Master"
master | Product: "2022.1.7" | Engine: DEFAULT (2712) | Path: "C:\Users\loure\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\loure\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2025 | Version: 25.0.2.419 | Build: 20240307_1300(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2025\"
Autodesk Revit 2024 | Version: 24.2.20.41 | Build: 20240814_1400(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
2022.1.7 | Version: 22.1.70.9 | Build: 20240704_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Comment by sanzoghenzo** [comment]
Hi @Pietieklipkop , we're (more or less) workin on it.

See #2384 fir the progress
