### ISSUE TITLE
[Bug]: I cant install neither latest version of PyRevit nor the version 4.8.10.22040. giving me an error message.

### ISSUE THREAD

**Issue by Mehrshad458** [pyrevitlabs/pyRevit#2444]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

![Screenshot (3)](https://github.com/user-attachments/assets/ffcabe1a-bf2a-436f-9d10-5a22ec1a7f7a)

### ⌨ Error/Debug Message

```shell
I need help with fixing this. I checked the installation step guide also and it didn't help.
Based on what I saw on the forum the latest PyRevit is not compatible with Revit 2025. I just marked the box so that I can submit the issue.
```

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Revit 2025.3
```

**Comment by sanzoghenzo** [comment]
@Mehrshad458 we created the issue template for a reason, we need all the info we can to help you.
Since you didn't post the output of the `pyrevit env` command, it's not clear:
- what the "latest version" of pyRevit is (I assume 4.8.16)
- what version of Revit you're using

As you already found out, revit 2025 is not supported. For it, you need the WIP installer.
If you're talking about revit 2024 and earlier, then those kind of bugs should be handled by following the troubleshooting guides to the T.

@jmcouffin should we put a giant banner about Revit 2025 somewhere? :rofl:

**Comment by jmcouffin** [comment]
@sanzoghenzo I kind of did... But maybe editing the issue template ...

**Comment by Mehrshad458** [comment]
@sanzoghenzo 
The Revit software version I'm using is Revit 2025.3 which I mentioned prior.
Yes the latest version of PyRevit I used was 4.8.16.
Can you explain what is WIP and where can I get the installation tutorial for it?

**Comment by jmcouffin** [comment]
> @sanzoghenzo The Revit software version I'm using is Revit 2025.3 which I mentioned prior. Yes the latest version of PyRevit I used was 4.8.16. Can you explain what is WIP and where can I get the installation tutorial for it?

https://www.pyrevitlabs.io/ use the orange yellowish button
or 
on github under the actions, check the pyRevitCI workflow, pick the latest run, then download the artefacts

**Comment by Mehrshad458** [comment]
Thankyou sir.
Is the PyRevit installation is going to work after installing WIP, or do I have to do any additional steps also?

**Comment by jmcouffin** [comment]
Uninstall previous versions beforehand. That's it

**Comment by Mehrshad458** [comment]
Thanks.
