### ISSUE TITLE
[Bug]: Color Splasher Errors on 5.0.0.24345+0715

### ISSUE THREAD

**Issue by Teflon98** [pyrevitlabs/pyRevit#2479]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Trying to launch Color Splasher in 2025 errors out.  Tried running it in 2024 and produces the same error.

![image](https://github.com/user-attachments/assets/8b57fbf3-d9b8-4f6f-8eb3-db5d4bc8e14a)

### ⌨ Error/Debug Message

```shell
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\--\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\ColorSplasher.pushbutton\script.py", line 158, in <module>
NameError: name 'UI' is not defined

Script Executor Traceback:
IronPython.Runtime.UnboundNameException: name 'UI' is not defined
 at IronPython.Runtime.Operations.PythonOps.GetVariable(CodeContext context, String name, Boolean isGlobal, Boolean lightThrow)
 at IronPython.Compiler.LookupGlobalInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

### ♻️ To Reproduce

Run Color Splasher from pyRevit menu

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive)
master | Deploy: "basepublic" | Branch: "master" | Version: "5.0.0.24345+0715-wip" | Path: "C:\Users\--\AppData\Roaming\pyRevit-Master"
==> Attachments
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
```

**Comment by jmcouffin** [comment]
Thanks.
I am in the middle of a PR to add more features and fix quite a few things. It should be fixed with #2457

**Comment by Teflon98** [comment]
> Thanks. I am in the middle of a PR to add more features and fix quite a few things. It should be fixed with #2457

I could have sworn I did a search and didn't find any recent Color Splash post.  Thanks again for the quick reply!

**Comment by jmcouffin** [comment]
check out the latest WIP installers under actions, it should get you going

**Comment by Teflon98** [comment]
pyRevit_5.0.0.2436+2256-wip

Thank you _very_ much for taking the time to get this working.  I've tested it on some walls, and while it does appear to work and reset, the warnings/log dialog appears.

It launches and splashes color but errors/warns when selecting Family;  **Family and Type**; **Type**; **Type ID**; as well as the 2nd **Type Name**.

```
('Exception type:', <type 'exceptions.ValueError'>)
('Exception value:', ValueError('invalid literal for float(): Curtain Wall 1',))
Traceback details:
File: C:\Users\--\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\ColorSplasher.pushbutton\script.py, Line: 1122, Function: get_range_values, Code: list_values = sorted(list_values, key=lambda x: float(x.value))
File: C:\Users\--\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\ColorSplasher.pushbutton\script.py, Line: 1122, Function: <lambda$1471>, Code: list_values = sorted(list_values, key=lambda x: float(x.value))
```

When Reset is hit after closing ColorSplasher and reopening it:
```
('Exception type:', <type 'exceptions.ValueError'>)
('Exception value:', ValueError('invalid literal for float(): Curtain Wall 1',))
Traceback details:
File: C:\Users\--\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\ColorSplasher.pushbutton\script.py, Line: 1122, Function: get_range_values, Code: list_values = sorted(list_values, key=lambda x: float(x.value))
File: C:\Users\--\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\ColorSplasher.pushbutton\script.py, Line: 1122, Function: <lambda$1471>, Code: list_values = sorted(list_values, key=lambda x: float(x.value))`
```

**Comment by jmcouffin** [comment]
> pyRevit_5.0.0.2436+2256-wip
> 
> Thank you _very_ much for taking the time to get this working. I've tested it on some walls, and while it does appear to work and reset, the warnings/log dialog appears.
> 
> It launches and splashes color but errors/warns when selecting Family; **Family and Type**; **Type**; **Type ID**; as well as the 2nd **Type Name**.
> 
> ```
> ('Exception type:', <type 'exceptions.ValueError'>)
> ('Exception value:', ValueError('invalid literal for float(): Curtain Wall 1',))
> Traceback details:
> File: C:\Users\--\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\ColorSplasher.pushbutton\script.py, Line: 1122, Function: get_range_values, Code: list_values = sorted(list_values, key=lambda x: float(x.value))
> File: C:\Users\--\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\ColorSplasher.pushbutton\script.py, Line: 1122, Function: <lambda$1471>, Code: list_values = sorted(list_values, key=lambda x: float(x.value))
> ```
> 
> When Reset is hit after closing ColorSplasher and reopening it:
> 
> ```
> ('Exception type:', <type 'exceptions.ValueError'>)
> ('Exception value:', ValueError('invalid literal for float(): Curtain Wall 1',))
> Traceback details:
> File: C:\Users\--\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\ColorSplasher.pushbutton\script.py, Line: 1122, Function: get_range_values, Code: list_values = sorted(list_values, key=lambda x: float(x.value))
> File: C:\Users\--\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\ColorSplasher.pushbutton\script.py, Line: 1122, Function: <lambda$1471>, Code: list_values = sorted(list_values, key=lambda x: float(x.value))`
> ```

Second error seems to be the exact same. Wrong copy paste I suppose.
I will have a look.
I have seen this issue but spent way too much time cleaning up the code, and I had to let it go in this state.
Now that the code is cleaner, I should be able to fix this quickly.

**Comment by Teflon98** [comment]
My apologies: I was getting a little too deep in the copy/pasting.  And you're totally right: I must have pasted the same thing twice.

Here's the result after closing the dialog; reopening the dialog; and hitting **Reset**.
```
('Exception type:', <type 'exceptions.TypeError'>)
('Exception value:', TypeError("'NoneType' object is not subscriptable",))
Traceback details:
File: C:\Users--\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\ColorSplasher.pushbutton\script.py, Line: 143, Function: Execute, Code: sel_par = wndw._list_box1.SelectedItem['Value']
```

**Comment by jmcouffin** [comment]
#2494 should fixe all that.
please try latest WIP installers: https://github.com/pyrevitlabs/pyRevit/actions/runs/12552503392
thanks for the logs, that helps.
If you get similar issues, please use the implemented debug mode shift+click on the color splasher button.

**Comment by BIMGSE** [comment]
I have the same problem : 

![Image](https://github.com/user-attachments/assets/0796739a-d580-4443-95e1-3cf3ca9c293f)

**Comment by jmcouffin** [comment]
> I have the same problem :

use latest release, this was fixed
